"""Obsah městských landing pages (tvorba webů <město>). Každé město má vlastní text, aby nešlo o duplicitní „doorway“ stránky."""

CITIES = [
    # --- Olomoucký kraj (15 000+ obyvatel) ---
    dict(slug='olomouc', name='Olomouc', loc='v Olomouci', gen='z Olomouce', kraj='Olomoucký kraj',
         intro='Navrhneme a postavíme web nebo e-shop pro vaši olomouckou firmu – moderní, srozumitelný a připravený na to, aby vás lidé našli na Googlu dřív než konkurenci.',
         text=['Olomouc je univerzitní a krajské město s obrovskou nabídkou služeb, gastra, ubytování i realit. Konkurence ve vyhledávání je tu vysoká – kdo chce, aby ho lidé z Olomouce našli, potřebuje web, který je na první pohled důvěryhodný a dobře postavený pro SEO.',
               'Pro olomoucké klienty tvoříme prezentační weby, e-shopy i redesigny starších stránek. Spolupráce probíhá online i osobně – z Jeseníku je to do Olomouce kousek, takže se rádi potkáme na kávě.'],
         who=['Služby a řemesla', 'Kavárny a restaurace', 'Reality', 'Ordinace a studia', 'Startupy', 'E-shopy'],
         faq=('Máte zkušenosti s konkurenčním prostředím v Olomouci?', 'Ano. Ve větším městě rozhoduje jasná nabídka, rychlá orientace na webu a lokální SEO – Google Firemní profil, obsah zaměřený na Olomouc a recenze. Na to web stavíme od začátku.')),
    dict(slug='prostejov', name='Prostějov', loc='v Prostějově', gen='z Prostějova', kraj='Olomoucký kraj',
         intro='Tvoříme weby a e-shopy pro firmy a podnikatele z Prostějova – s důrazem na design, který prodává, a na dohledatelnost ve vyhledávačích.',
         text=['Prostějov, kterému se přezdívá Hanácké Athény, má silnou tradici oděvnictví a módy. Pro značky, které stojí na stylu, je kvalitní web a e-shop stejně důležitý jako výloha na náměstí.',
               'Pomůžeme s firemním webem, e-shopem s oblečením či doplňky i s prezentací služeb. Vše řešíme online, a když je potřeba, přijedeme osobně.'],
         who=['Móda a oděvy', 'Výroba', 'Služby', 'Gastro', 'Řemeslníci', 'E-shopy'],
         faq=('Zvládnete e-shop pro módní značku z Prostějova?', 'Ano. U módy rozhodují fotky, přehledné varianty velikostí a barev a jednoduchý nákup na mobilu. Navrhneme e-shop, který vaši značku ukáže v nejlepším světle.')),
    dict(slug='prerov', name='Přerov', loc='v Přerově', gen='z Přerova', kraj='Olomoucký kraj',
         intro='Webové stránky na míru pro přerovské firmy – od technických prezentací výroby po weby pro služby a obchody.',
         text=['Přerov je známý průmyslem – optikou, strojírenstvím a chemií – a zároveň je přirozeným centrem služeb pro celé okolí. Technické firmy potřebují web, který srozumitelně vysvětlí, co umí, a služby zase web, který rychle vede k poptávce.',
               'Máme zkušenosti s prezentací výrobních firem (podívejte se na referenci KONRADT – CNC obrábění) i s weby pro menší podnikatele. Spolupracovat můžeme online i osobně.'],
         who=['Výroba a strojírenství', 'B2B firmy', 'Služby', 'Obchody', 'Řemeslníci', 'Gastro'],
         faq=('Umíte web pro výrobní nebo B2B firmu z Přerova?', 'Ano. U výrobních firem stavíme na přehledné prezentaci technologií, výrobních možností a referencí – a na SEO pro konkrétní služby, které zákazníci hledají.')),
    dict(slug='sumperk', name='Šumperk', loc='v Šumperku', gen='ze Šumperka', kraj='Olomoucký kraj',
         intro='Tvorba webových stránek pro Šumperk a okolí – weby pro ubytování, turistické služby, výrobu i místní podnikatele.',
         text=['Šumperk je bránou Jeseníků. Kromě výrobních firem je tu spousta ubytování, sportovních a turistických služeb, které potřebují oslovit hosty z celé republiky – a často i ze zahraničí.',
               'Jsme od Šumperka kousek, takže se rádi potkáme osobně. Pro ubytování umíme weby s rezervacemi a jazykovými verzemi, pro firmy přehledné prezentace s důrazem na poptávky.'],
         who=['Ubytování', 'Turistické služby', 'Výroba', 'Řemeslníci', 'Gastro', 'Obchody'],
         faq=('Uděláte web pro penzion nebo apartmány v okolí Šumperka?', 'Ano, to je naše parketa. Web s kvalitními fotkami, přehledem pokojů a cen, rezervačním formulářem a jazykovými verzemi (DE, PL, EN), aby hosté rezervovali napřímo.')),
    dict(slug='hranice', name='Hranice', loc='v Hranicích', gen='z Hranic', kraj='Olomoucký kraj',
         intro='Moderní weby a e-shopy pro firmy z Hranic na Moravě – navržené tak, aby přiváděly poptávky.',
         text=['Hranice leží na důležité dopravní křižovatce a kromě průmyslu a logistiky láká i turisty – Hranická propast nebo nedaleké lázně Teplice nad Bečvou. Místní firmy proto oslovují zákazníky z celého regionu i z dálky.',
               'Pro hranické klienty tvoříme firemní weby, e-shopy a weby pro služby cestovního ruchu. Komunikujeme online, osobní schůzka je samozřejmě možná.'],
         who=['Logistika a doprava', 'Výroba', 'Turismus', 'Služby', 'Gastro', 'Řemeslníci'],
         faq=('Pomůžete firmě z Hranic oslovit zákazníky z celého regionu?', 'Ano. Kombinujeme lokální SEO pro Hranice s obsahem pro okolní města a celý region, takže vás najdou zákazníci z Přerovska, Valašska i dál.')),
    dict(slug='zabreh', name='Zábřeh', loc='v Zábřehu', gen='ze Zábřehu', kraj='Olomoucký kraj',
         intro='Tvorba webových stránek pro Zábřeh a Zábřežsko – weby a e-shopy pro místní firmy, řemeslníky i služby.',
         text=['Zábřeh je přirozeným centrem Zábřežska mezi Šumperkem a Mohelnicí. Působí tu výrobní firmy, řemeslníci i spousta služeb, které soupeří o zákazníky z celého okolí – a ti dnes hledají hlavně na Googlu.',
               'Do Zábřehu to máme z Jeseníku kousek, takže úvodní schůzku rádi uděláme osobně. Tvoříme prezentační weby, e-shopy i redesigny starších stránek.'],
         who=['Výroba', 'Řemeslníci', 'Služby', 'Obchody', 'Gastro', 'Ubytování'],
         faq=('Přijedete za námi do Zábřehu osobně?', 'Ano. Zábřeh máme z Jeseníku blízko, úvodní schůzku rádi uděláme u vás. Zbytek spolupráce pak běží pohodlně online.')),
    dict(slug='mohelnice', name='Mohelnice', loc='v Mohelnici', gen='z Mohelnice', kraj='Olomoucký kraj',
         intro='Weby na míru pro firmy z Mohelnice – technické prezentace pro výrobu i srozumitelné weby pro služby.',
         text=['Mohelnice má výhodnou dopravní polohu a silnou průmyslovou zónu s řadou výrobních firem a dodavatelů. Vedle průmyslu tu fungují služby a obchody pro celé Mohelnicko.',
               'Pro mohelnické firmy tvoříme technické prezentace, weby pro služby i e-shopy. Jsme kousek, takže se rádi potkáme osobně.'],
         who=['Výroba a automotive', 'Dodavatelé', 'Služby', 'Řemeslníci', 'Obchody', 'Gastro'],
         faq=('Uděláte web pro výrobní firmu z Mohelnice?', 'Ano. Výrobní firmy prezentujeme přehledně – technologie, kapacity, certifikace a reference, aby web pomáhal i při náboru a jednání s odběrateli.')),
    dict(slug='unicov', name='Uničov', loc='v Uničově', gen='z Uničova', kraj='Olomoucký kraj',
         intro='Tvorba webových stránek pro Uničov – moderní weby pro firmy, řemesla a služby.',
         text=['Uničov se strojírenskou tradicí a historickým náměstím je centrem Uničovska. Místní firmy a živnostníci potřebují web, který je ukáže lidem z Uničova, Litovle i Šternberka.',
               'Tvoříme prezentační weby, e-shopy a technické prezentace firem. Spolupráce probíhá online i osobně.'],
         who=['Strojírenství', 'Výroba', 'Řemeslníci', 'Služby', 'Obchody', 'Gastro'],
         faq=('Pomůžete firmě z Uničova oslovit zákazníky z okolí?', 'Ano. Obsah webu a lokální SEO zaměříme na Uničov i okolní města, takže vás najdou zákazníci z celého Uničovska a Olomoucka.')),
    dict(slug='litovel', name='Litovel', loc='v Litovli', gen='z Litovle', kraj='Olomoucký kraj',
         intro='Weby a e-shopy pro firmy z Litovle – srozumitelné, moderní a postavené na poptávky.',
         text=['Litovel, přezdívaná Hanácké Benátky a známá svým pivovarem, leží v srdci Hané nedaleko Olomouce. Místní firmy, řemeslníci a služby oslovují zákazníky z Litovelska i z krajského města.',
               'Litovelským klientům tvoříme prezentační weby, e-shopy i weby pro gastro a turismus. Spolupracujeme online i osobně.'],
         who=['Služby', 'Řemeslníci', 'Gastro', 'Turismus', 'Výroba', 'E-shopy'],
         faq=('Uděláte web pro restauraci nebo penzion v Litovli?', 'Ano. Navrhneme web s menu, fotkami, otevírací dobou a rezervací, propojený s Google Firemním profilem, aby vás hosté snadno našli.')),
    # --- Moravskoslezský kraj (20 000+ obyvatel + Bruntál) ---
    dict(slug='ostrava', name='Ostrava', loc='v Ostravě', gen='z Ostravy', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro ostravské firmy – weby a e-shopy na míru, které obstojí i v konkurenci velkého města.',
         text=['Ostrava je třetím největším městem Česka, centrem průmyslu, technologií i kultury. Ve vyhledávání tu o zákazníky soupeří stovky firem, a proto rozhoduje kvalita webu, jasná nabídka a promyšlené SEO.',
               'Ostravským klientům dodáváme firemní weby, e-shopy, landing pages pro kampaně i redesigny. Celá spolupráce běží online – rychle, přehledně a s jedním kontaktním člověkem.'],
         who=['Technologické firmy', 'Průmysl a B2B', 'Služby', 'Gastro a kluby', 'Reality', 'E-shopy'],
         faq=('Jak se prosadit s webem v konkurenci ostravských firem?', 'Kombinací kvalitního obsahu, rychlé orientace a cíleného SEO na služby a čtvrti, kde působíte. K tomu Google Firemní profil a případně PPC kampaně – všechno pod jednou střechou Yesmark.')),
    dict(slug='havirov', name='Havířov', loc='v Havířově', gen='z Havířova', kraj='Moravskoslezský kraj',
         intro='Weby na míru pro havířovské podnikatele a firmy – moderní design, srozumitelný obsah a jasná cesta k poptávce.',
         text=['Havířov je mladé statutární město s velkou koncentrací služeb, obchodů a menších firem. Zákazníci tu nejčastěji hledají služby „v Havířově“ přímo na mobilu – web proto musí být přehledný a rychle vést k telefonu nebo formuláři.',
               'Pro havířovské klienty tvoříme prezentační weby, e-shopy a weby pro služby. Spolupráce probíhá online, s jasným harmonogramem a cenou předem.'],
         who=['Služby', 'Obchody', 'Řemeslníci', 'Fitness a zdraví', 'Gastro', 'E-shopy'],
         faq=('Uděláte web pro malou firmu nebo živnostníka z Havířova?', 'Určitě. Pro menší podnikatele máme prezentační weby od 9 900 Kč – s přehlednou nabídkou služeb, kontakty a formulářem, aby vás zákazníci rychle našli a ozvali se.')),
    dict(slug='opava', name='Opava', loc='v Opavě', gen='z Opavy', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Opavu a Opavsko – weby a e-shopy, které působí profesionálně a přivádí zákazníky.',
         text=['Opava, historické hlavní město Slezska, je univerzitním a správním centrem s živou scénou služeb, kultury i řemesel. Místní firmy stojí na důvěře a dobrém jménu – a to by měl odrážet i web.',
               'Opavským klientům pomáháme s novými weby, e-shopy i modernizací starších stránek. Komunikujeme online, a když je potřeba, přijedeme.'],
         who=['Služby', 'Řemesla', 'Kultura a gastro', 'Výroba', 'Zdravotnictví', 'E-shopy'],
         faq=('Pomůžete nám s webem pro Opavu i okolní obce?', 'Ano. Web postavíme tak, aby vás našli lidé z Opavy i z okolí – obsah zaměříme na místa, kde působíte, a propojíme ho s Google Firemním profilem.')),
    dict(slug='frydek-mistek', name='Frýdek-Místek', loc='ve Frýdku-Místku', gen='z Frýdku-Místku', kraj='Moravskoslezský kraj',
         intro='Webové stránky a e-shopy pro firmy z Frýdku-Místku – od služeb a řemesel po turistické podniky v Beskydech.',
         text=['Frýdek-Místek je branou Beskyd. Kromě firem a služeb pro místní je tu silný cestovní ruch – ubytování, sport a outdoor, které potřebují oslovit návštěvníky z celé republiky.',
               'Tvoříme weby pro místní podnikatele i pro beskydské ubytování s rezervacemi a jazykovými verzemi. Spolupráce probíhá online, rychle a přehledně.'],
         who=['Ubytování v Beskydech', 'Sport a outdoor', 'Služby', 'Řemeslníci', 'Výroba', 'Gastro'],
         faq=('Zvládnete web pro ubytování v Beskydech?', 'Ano. Navrhneme web s fotkami, ceníkem, kalendářem obsazenosti nebo rezervačním formulářem, aby hosté rezervovali napřímo bez provizí rezervačním portálům.')),
    dict(slug='karvina', name='Karviná', loc='v Karviné', gen='z Karviné', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Karvinou – moderní weby a e-shopy pro firmy, služby i podnikatele.',
         text=['Karviná je město lázní Darkov, vysokoškolských studentů a stále více služeb a menších firem. Ať nabízíte služby místním, nebo prodáváte po celé republice, web je dnes první místo, kde vás zákazník posuzuje.',
               'Karvinským klientům tvoříme prezentační weby, e-shopy i weby s vícejazyčnou verzí pro polské zákazníky. Spolupráce běží online.'],
         who=['Služby', 'Zdraví a wellness', 'Obchody', 'Řemeslníci', 'Gastro', 'E-shopy'],
         faq=('Umíte web i v polštině pro zákazníky z Polska?', 'Ano. Připravíme jazykovou verzi webu (PL, případně DE a EN), aby vás našli a pochopili i zákazníci za hranicemi.')),
    dict(slug='trinec', name='Třinec', loc='v Třinci', gen='z Třince', kraj='Moravskoslezský kraj',
         intro='Weby na míru pro firmy z Třince a okolí – průmysl, služby i beskydský cestovní ruch.',
         text=['Třinec je spojený s železárnami a průmyslem, ale také s Beskydy a česko-polským pomezím. Na webu tu proto často hraje roli dvojjazyčnost a srozumitelná prezentace technických služeb.',
               'Tvoříme firemní weby pro dodavatele a výrobní firmy, prezentace služeb i weby pro ubytování. Spolupráce probíhá online, v češtině i s polskou jazykovou verzí webu.'],
         who=['Průmysl a dodavatelé', 'Služby', 'Ubytování v Beskydech', 'Řemeslníci', 'Gastro', 'E-shopy'],
         faq=('Zvládnete web pro dodavatele průmyslu z Třince?', 'Ano. Postavíme web, který přehledně ukáže technologie, certifikace a reference – a díky SEO vás najdou noví odběratelé, kteří hledají konkrétní služby.')),
    dict(slug='orlova', name='Orlová', loc='v Orlové', gen='z Orlové', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Orlovou – srozumitelné weby, které místním firmám přivádí zákazníky.',
         text=['Orlová patří ke Karvinsku s bohatou hornickou tradicí. Dnes tu převažují služby, obchody a menší firmy, které soupeří o zákazníky z celého okolí – od Karviné po Bohumín.',
               'Orlovským podnikatelům tvoříme prezentační weby a e-shopy, které jsou přehledné na mobilu a vedou k poptávce. Vše vyřešíme online.'],
         who=['Služby', 'Řemeslníci', 'Obchody', 'Zdraví a krása', 'Gastro', 'Živnostníci'],
         faq=('Má smysl web pro malou firmu z Orlové?', 'Ano. Většina zákazníků dnes hledá služby na Googlu. I jednoduchý, dobře postavený web s Google Firemním profilem přinese poptávky, které by jinak skončily u konkurence.')),
    dict(slug='cesky-tesin', name='Český Těšín', loc='v Českém Těšíně', gen='z Českého Těšína', kraj='Moravskoslezský kraj',
         intro='Weby pro firmy z Českého Těšína – v češtině i polštině, pro zákazníky z obou stran hranice.',
         text=['Český Těšín tvoří s polským Cieszynem jedno přirozené město rozdělené řekou Olzou. Místní firmy proto často obsluhují zákazníky z Česka i Polska – a jejich web by měl mluvit oběma jazyky.',
               'Tvoříme dvojjazyčné weby a e-shopy, prezentace služeb i obchodů. Spolupráce probíhá online, s jasnou cenou a termínem.'],
         who=['Obchody', 'Služby', 'Gastro', 'Ubytování', 'Řemeslníci', 'E-shopy'],
         faq=('Uděláte web v češtině i polštině?', 'Ano. Postavíme web s plnohodnotnou polskou verzí a SEO pro obě jazykové mutace, aby vás našli zákazníci z Českého Těšína i z Cieszyna.')),
    dict(slug='novy-jicin', name='Nový Jičín', loc='v Novém Jičíně', gen='z Nového Jičína', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Nový Jičín – weby a e-shopy pro firmy, řemesla i služby.',
         text=['Nový Jičín, město klobouků a krásného náměstí s podloubím, je centrem Novojičínska s řadou výrobních firem, řemeslníků i služeb. Kvalitní web tu pomáhá oslovit zákazníky z celého regionu.',
               'Novojičínským klientům tvoříme firemní weby, e-shopy i weby pro služby a cestovní ruch. Komunikujeme online a s osobním přístupem.'],
         who=['Výroba', 'Řemesla', 'Služby', 'Obchody', 'Gastro', 'E-shopy'],
         faq=('Zvládnete e-shop pro řemeslnou výrobu z Nového Jičína?', 'Ano. Navrhneme e-shop, který vynikne fotkami, příběhem výrobků a jednoduchým nákupem – včetně plateb a dopravy.')),
    dict(slug='krnov', name='Krnov', loc='v Krnově', gen='z Krnova', kraj='Moravskoslezský kraj',
         intro='Weby na míru pro firmy z Krnova a okolí – od řemesel a výroby po služby a cestovní ruch.',
         text=['Krnov, známý tradicí výroby varhan, leží na pomezí Jeseníků a Polska. Místní firmy tak oslovují zákazníky z Krnovska, Bruntálska i ze zahraničí.',
               'Krnov máme z Jeseníku kousek, takže se rádi potkáme i osobně. Tvoříme firemní weby, e-shopy a weby s polskou nebo německou jazykovou verzí.'],
         who=['Výroba a řemesla', 'Služby', 'Obchody', 'Turismus', 'Gastro', 'E-shopy'],
         faq=('Přijedete za námi do Krnova osobně?', 'Ano, z Jeseníku to máme kousek. Úvodní schůzku rádi uděláme u vás, zbytek spolupráce pak běží pohodlně online.')),
    dict(slug='koprivnice', name='Kopřivnice', loc='v Kopřivnici', gen='z Kopřivnice', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Kopřivnici – weby pro výrobní firmy, dodavatele i místní služby.',
         text=['Kopřivnice je spojená s Tatrou a automobilovou tradicí. Kolem výroby tu funguje řada dodavatelů a technických firem, ale také služby a obchody pro místní i návštěvníky Lašska a Beskyd.',
               'Pro kopřivnické klienty tvoříme technické prezentace firem, weby pro služby i e-shopy. Spolupráce probíhá online.'],
         who=['Automotive a dodavatelé', 'Výroba', 'Služby', 'Řemeslníci', 'Turismus', 'E-shopy'],
         faq=('Uděláte web pro technickou firmu z Kopřivnice?', 'Ano. Technické firmy prezentujeme přehledně – výrobní možnosti, technologie, certifikace a reference. Inspiraci najdete v naší referenci KONRADT.')),
    dict(slug='bohumin', name='Bohumín', loc='v Bohumíně', gen='z Bohumína', kraj='Moravskoslezský kraj',
         intro='Weby a e-shopy pro firmy z Bohumína – pro zákazníky z Česka i Polska.',
         text=['Bohumín je významný železniční uzel s průmyslovou tradicí přímo na hranici s Polskem. Místní firmy proto často obsluhují zákazníky z obou zemí a z celého Ostravska.',
               'Tvoříme firemní weby, e-shopy a weby s polskou jazykovou verzí. Spolupráce probíhá online, s pevnou cenou a termínem.'],
         who=['Průmysl a logistika', 'Služby', 'Obchody', 'Řemeslníci', 'Gastro', 'E-shopy'],
         faq=('Zvládnete web pro firmu, která obsluhuje i Polsko?', 'Ano. Připravíme polskou verzi webu a obsah zaměříme tak, aby vás našli zákazníci z Bohumína, Ostravska i z polské strany hranice.')),
    dict(slug='bruntal', name='Bruntál', loc='v Bruntále', gen='z Bruntálu', kraj='Moravskoslezský kraj',
         intro='Tvorba webových stránek pro Bruntál a Bruntálsko – weby pro ubytování v Jeseníkách, služby i výrobní firmy.',
         text=['Bruntál se zámkem a blízkostí Pradědu je přirozenou branou do Jeseníků. Kromě místních firem a služeb je tu silný cestovní ruch – od Karlovy Studánky po Malou Morávku.',
               'Z Jeseníku jsme v Bruntále rychle, takže se rádi potkáme osobně. Tvoříme weby pro ubytování s rezervacemi, prezentace firem i e-shopy.'],
         who=['Ubytování v Jeseníkách', 'Turismus a sport', 'Služby', 'Výroba', 'Řemeslníci', 'Gastro'],
         faq=('Uděláte web pro ubytování na Bruntálsku?', 'Ano, weby pro ubytování v Jeseníkách děláme rádi a často. S fotkami, ceníkem, rezervačním formulářem a jazykovými verzemi, aby hosté rezervovali napřímo.')),
    # --- Pardubický kraj (20 000+ obyvatel) ---
    dict(slug='pardubice', name='Pardubice', loc='v Pardubicích', gen='z Pardubic', kraj='Pardubický kraj',
         intro='Tvorba webových stránek pro pardubické firmy – weby a e-shopy na míru, které obstojí v konkurenci krajského města.',
         text=['Pardubice – město perníku, Velké pardubické a univerzity – jsou krajským centrem s rozvinutým průmyslem, službami i obchodem. Konkurence ve vyhledávání je tu velká a o zákazníka rozhoduje první dojem z webu.',
               'Pardubickým klientům tvoříme firemní weby, e-shopy, landing pages i redesigny. Celá spolupráce běží online – rychle, přehledně a s jedním kontaktním člověkem.'],
         who=['Služby', 'Průmysl a B2B', 'Obchody', 'Gastro', 'Reality', 'E-shopy'],
         faq=('Spolupracujete s klienty z Pardubic na dálku?', 'Ano, a funguje to skvěle. Konzultace, návrhy i předání řešíme online – telefonem, videohovorem a e-mailem. Klient má po celou dobu jeden kontakt a jasný harmonogram.')),
    dict(slug='chrudim', name='Chrudim', loc='v Chrudimi', gen='z Chrudimi', kraj='Pardubický kraj',
         intro='Weby na míru pro firmy z Chrudimi – moderní design, dobrá dohledatelnost a jasná cesta k poptávce.',
         text=['Chrudim, město loutek s krásným historickým centrem, je zázemím pro řadu výrobních firem, řemeslníků i služeb. Zákazníci z Chrudimska dnes hledají hlavně online – a web je jejich první zastávka.',
               'Chrudimským klientům tvoříme prezentační weby, e-shopy i redesigny. Spolupráce probíhá online, s pevnou cenou a termínem.'],
         who=['Výroba', 'Řemeslníci', 'Služby', 'Obchody', 'Kultura a gastro', 'E-shopy'],
         faq=('Má smysl nový web pro zavedenou firmu z Chrudimi?', 'Ano, pokud je ten současný zastaralý, nefunguje dobře na mobilu nebo nepřináší poptávky. Redesign s novým obsahem a SEO často výrazně zvýší počet poptávek.')),
]
