"""Oborové landing pages – část C: služby a profese, výroba a B2B, komunita, ostatní."""

C = [
# ---------------- Služby a profese ----------------
dict(slug='ucetni', name='Web pro účetní a daňovou kancelář', short='účetní kancelář', group='Služby a profese',
  problem='Podnikatelé hledají účetní hlavně podle doporučení – a pak si ji ověří na webu. Pokud tam nenajdou, pro koho pracujete, jak spolupráce probíhá a orientační cenu, osloví někoho jiného.',
  must=['Pro koho pracujete (OSVČ, s.r.o., plátci DPH, neziskovky)', 'Služby (účetnictví, daně, mzdy, DPH, zastupování)', 'Orientační ceník nebo princip cenotvorby', 'Jak probíhá předávání dokladů (online, osobně)', 'Termíny a důležité daňové lhůty', 'Certifikace a pojištění', 'Reference', 'Poptávkový formulář'],
  pages=['Úvod', 'Služby', 'Ceník', 'Jak spolupracujeme', 'O kanceláři', 'Daňový kalendář', 'Kontakt'],
  features=['Poptávkový formulář', 'Bezpečné nahrávání dokladů (klientská zóna)', 'Newsletter s termíny'],
  seo=['„Účetní + město“, „daňové přiznání + město“', 'Sezónní obsah (daňové přiznání, přehledy)', 'Daňový kalendář'],
  faq=[('Má smysl uvádět ceník účetnictví?', 'Orientační ano – např. podle počtu dokladů. Podnikatelé rádi vidí cenu dopředu a poptávky jsou kvalitnější.'),
       ('Jak web pomůže v sezóně daňových přiznání?', 'Stránkou o daňových přiznáních, která se každý rok v lednu až březnu zobrazuje lidem, kteří hledají pomoc.')]),
dict(slug='advokat', name='Web pro advokáta a advokátní kancelář', short='advokátní kancelář', group='Služby a profese',
  problem='Klient hledá advokáta s konkrétním problémem – rozvod, dědictví, vymáhání, nemovitosti. Obecný web „poskytujeme komplexní právní služby“ mu nic neřekne.',
  must=['Oblasti práva srozumitelně pro laiky', 'Profily advokátů a specializace', 'Jak probíhá první konzultace a kolik stojí', 'Způsob odměňování', 'Kontaktní formulář s popisem věci', 'Články a právní rady', 'Kontakt, mapa', 'Splnění pravidel ČAK pro prezentaci'],
  pages=['Úvod', 'Oblasti práva', 'Tým', 'Odměna', 'Články', 'Kontakt'],
  features=['Diskrétní formulář', 'Rezervace konzultace', 'Blog'],
  seo=['„Advokát + město“ a konkrétní oblasti („rozvod advokát + město“)', 'Odborné články na časté otázky', 'Stránky pro jednotlivé oblasti práva'],
  faq=[('Může advokát propagovat svoje služby na webu?', 'Ano, ve věcné a důstojné formě podle pravidel ČAK. Web postavíme tak, aby byl informativní a profesionální.'),
       ('Přinášejí právní články klienty?', 'Ano – lidé hledají odpovědi na konkrétní problém a článek je přivede k vám.')]),
dict(slug='realitni-makler', name='Web pro realitního makléře', short='realitní makléř', group='Služby a profese', ref='reality',
  problem='Prodávající si vybírá makléře, kterému věří. Web makléře je především osobní značka – musí ukázat znalost regionu, výsledky a přístup. Pouhý výpis nemovitostí z realitního software nestačí.',
  must=['Osobní příběh a přístup', 'Aktuální nabídka nemovitostí (napojení na realitní software)', 'Prodané nemovitosti a výsledky', 'Recenze klientů', 'Odhad ceny nemovitosti zdarma', 'Znalost regionu', 'Blog o realitách', 'Kontakt'],
  pages=['Úvod', 'Nabídka', 'Prodáno', 'Chci prodat', 'Odhad ceny', 'O mně', 'Recenze', 'Blog', 'Kontakt'],
  features=['Import nabídky z realitního software', 'Formulář pro odhad ceny', 'Newsletter'],
  seo=['„Realitní makléř + město“, „prodej nemovitosti + region“', 'Obsah o trhu v regionu', 'Recenze'],
  faq=[('Jde napojit nabídku z realitního software?', 'Ano – nemovitosti se na web importují automaticky, nic nepřepisujete ručně.'),
       ('Co nejvíc získává nové prodávající?', 'Formulář „odhad ceny zdarma“ a recenze s výsledky prodeje. Podívejte se na naši referenci Moniky Veličkové.')]),
dict(slug='financni-poradce', name='Web pro finančního poradce', short='finanční poradce', group='Služby a profese',
  problem='Finanční poradenství stojí na důvěře, ale weby poradců často působí jako leták nadnárodní sítě. Klient chce poznat člověka, jeho přístup a vědět, jak se platí.',
  must=['Osobní představení a přístup', 'S čím pomáháte (hypotéky, investice, pojištění, penze)', 'Jak probíhá spolupráce a odměna', 'Kalkulačky (hypotéka, spoření)', 'Recenze klientů', 'Registrace u ČNB', 'Rezervace schůzky', 'Kontakt'],
  pages=['Úvod', 'Služby', 'Hypotéky', 'Investice', 'Kalkulačky', 'O mně', 'Recenze', 'Kontakt'],
  features=['Kalkulačky', 'Rezervace schůzek', 'Newsletter'],
  seo=['„Hypoteční poradce + město“, „finanční poradce + město“', 'Články a kalkulačky', 'Recenze'],
  faq=[('Má smysl mít vlastní web vedle stránky od společnosti?', 'Ano – firemní stránka nebuduje vaši osobní značku a nepřivede klienty z vašeho regionu.'),
       ('Pomáhají kalkulačky?', 'Ano, zvyšují čas na webu a přivádějí lidi, kteří řeší konkrétní rozhodnutí.')]),
dict(slug='autoskola', name='Web pro autoškolu', short='autoškola', group='Služby a profese',
  problem='Budoucí řidiči (a jejich rodiče) porovnávají autoškoly podle ceny, termínů a úspěšnosti. Web bez jasného ceníku a přihlášky online přichází o žáky.',
  must=['Ceník podle skupin (B, A, C…)', 'Termíny kurzů', 'Online přihláška', 'Vozový park', 'Instruktoři', 'Úspěšnost u zkoušek', 'Průběh výcviku krok za krokem', 'Kontakt'],
  pages=['Úvod', 'Skupiny a ceník', 'Termíny', 'Přihláška', 'Průběh výcviku', 'Instruktoři', 'Kontakt'],
  features=['Online přihláška', 'Platba zálohy', 'Kalendář kurzů'],
  seo=['„Autoškola + město“, „řidičák cena + město“', 'Stránky skupin', 'Recenze absolventů'],
  faq=[('Jde přes web přihlašovat žáky?', 'Ano, včetně platby zálohy – přihláška vám přijde e-mailem se všemi údaji.'),
       ('Co nejvíc rozhoduje o výběru autoškoly?', 'Cena, termín a recenze. Všechno musí být na webu vidět na první pohled.')]),
dict(slug='jazykova-skola', name='Web pro jazykovou školu a lektora', short='jazyková škola / lektor', group='Služby a profese',
  problem='Studenti hledají kurz podle jazyka, úrovně a času. Když na webu nenajdou rozvrh, cenu a možnost přihlásit se, napíšou konkurenci.',
  must=['Nabídka jazyků a úrovní', 'Rozvrh kurzů a termíny', 'Ceník a slevy', 'Online přihláška a platba', 'Lektoři', 'Firemní výuka', 'Online výuka', 'Rozřazovací test'],
  pages=['Úvod', 'Kurzy', 'Rozvrh', 'Ceník', 'Firemní výuka', 'Lektoři', 'Přihláška'],
  features=['Online přihláška a platba', 'Rozřazovací test', 'Rezervace individuálních lekcí'],
  seo=['„Angličtina + město“, „kurz němčiny + město“', 'Stránka pro každý jazyk', 'Firemní výuka'],
  faq=[('Jde na web dát rozřazovací test?', 'Ano – jednoduchý online test doporučí úroveň a rovnou nabídne vhodný kurz.'),
       ('Má lektor jednotlivec potřebu webu?', 'Ano – i jednoduchý web s nabídkou, cenou a rezervací přivede studenty z okolí i online.')]),
dict(slug='doucovani', name='Web pro doučování', short='doučování', group='Služby a profese',
  problem='Rodiče hledají doučování narychlo – před přijímačkami nebo pololetím. Potřebují vidět předměty, cenu, termíny a důvěryhodného lektora.',
  must=['Předměty a ročníky', 'Příprava na přijímačky a maturitu', 'Ceník lekcí a balíčků', 'Online i osobní výuka', 'Lektoři a výsledky', 'Rezervace lekce', 'Recenze rodičů', 'Kontakt'],
  pages=['Úvod', 'Předměty', 'Přijímačky', 'Ceník', 'Lektoři', 'Rezervace'],
  features=['Rezervace lekcí', 'Platba balíčků', 'Recenze'],
  seo=['„Doučování matematiky + město“, „příprava na přijímačky + město“', 'Sezónní obsah', 'Recenze'],
  faq=[('Kdy je nejvyšší poptávka po doučování?', 'Před přijímačkami, pololetím a maturitou. Web je potřeba mít připravený s předstihem.'),
       ('Jak prodávat balíčky lekcí?', 'Online platbou balíčku se slevou – rodiče to ocení a vy máte jistotu.')]),
dict(slug='fotograf', name='Web pro fotografa', short='fotograf', group='Služby a profese',
  problem='Fotograf bez portfolia na vlastním webu je závislý na sociálních sítích. Klienti ale hledají „fotograf + město“ na Googlu – a tam vyhrává rychlý web s jasnou nabídkou a cenami.',
  must=['Portfolio podle typu focení', 'Ceník a balíčky', 'Rezervace termínu / poptávka', 'O mně – styl a přístup', 'Recenze', 'Průběh focení a předání fotek', 'Dárkové poukazy', 'Rychlé načítání fotek'],
  pages=['Úvod', 'Portfolio', 'Rodinné focení', 'Portréty', 'Firmy', 'Ceník', 'Poukazy', 'Kontakt'],
  features=['Optimalizace fotek', 'Klientské galerie', 'Prodej poukazů'],
  seo=['„Fotograf + město“ a typy focení', 'Blog s příběhy focení', 'Alt texty fotek'],
  faq=[('Jak udělat portfolio, které prodává?', 'Méně je víc – vybrané nejlepší fotky podle typu focení a jasná cesta k ceníku a poptávce.'),
       ('Dají se na webu prodávat poukazy na focení?', 'Ano, s online platbou – oblíbený dárek k Vánocům a narozeninám.')]),
dict(slug='prekladatel', name='Web pro překladatele a tlumočníka', short='překladatel / tlumočník', group='Služby a profese',
  problem='Zákazníci potřebují překlad rychle a chtějí znát cenu dopředu. Web, kam nejde nahrát dokument a dostat nabídku, prohrává s agenturami.',
  must=['Jazykové kombinace', 'Typy překladů (soudní, odborné, webové)', 'Ceník za normostranu', 'Nahrání dokumentu a rychlá nabídka', 'Termíny dodání', 'Tlumočení', 'Reference a specializace', 'Kontakt'],
  pages=['Úvod', 'Překlady', 'Soudní překlady', 'Tlumočení', 'Ceník', 'Poptávka'],
  features=['Formulář s nahráním dokumentu', 'Jazykové verze webu', 'Recenze'],
  seo=['„Soudní překlad + jazyk + město“', 'Stránky jazykových kombinací', 'Vícejazyčný web'],
  faq=[('Má být web překladatele vícejazyčný?', 'Ideálně ano – alespoň v jazycích, ze kterých a do kterých překládáte.'),
       ('Jak zrychlit nabídky?', 'Formulářem s nahráním dokumentu – vidíte rozsah hned a nabídku pošlete během pár minut.')]),
dict(slug='architekt', name='Web pro architekta a interiérového designéra', short='architekt / interiérový designér', group='Služby a profese',
  problem='Architektura se prodává vizuálně a příběhem. Web musí být sám o sobě ukázkou dobrého designu – a zároveň vysvětlit, jak spolupráce probíhá a kolik stojí.',
  must=['Portfolio projektů s příběhem', 'Služby (studie, projekt, interiér, autorský dozor)', 'Postup spolupráce', 'Princip honoráře', 'O studiu', 'Ocenění a publikace', 'Poptávka', 'Kontakt'],
  pages=['Úvod', 'Projekty', 'Služby', 'Jak pracujeme', 'Studio', 'Kontakt'],
  features=['Velkoplošné galerie', 'Poptávkový formulář', 'Rychlé načítání'],
  seo=['„Architekt + město“, „návrh interiéru + město“', 'Projekty s lokalitou', 'Články o architektuře'],
  faq=[('Jak ukázat projekt, který ještě není postavený?', 'Vizualizacemi a příběhem – zadání, řešení, materiály. Klient vidí způsob myšlení.'),
       ('Má mít architekt na webu ceny?', 'Alespoň princip honoráře (procento z investice, cena za m²). Klienti oceňují transparentnost.')]),
# ---------------- Výroba a B2B ----------------
dict(slug='strojirenska-firma', name='Web pro strojírenskou a výrobní firmu', short='strojírenská firma', group='Výroba a B2B', ref='konradt',
  problem='Nákupčí hledají dodavatele podle technologií, kapacit a certifikací. Výrobní firmy přitom mívají weby, které jsou zastaralé, bez technických parametrů a bez možnosti poslat výkres.',
  must=['Technologie a strojový park s parametry', 'Materiály a tolerance', 'Certifikace (ISO…)', 'Reference a odběratelé', 'Poptávka s nahráním výkresu (STEP, DXF, PDF)', 'Jazykové verze (DE, EN)', 'Kariéra', 'Kontakt'],
  pages=['Úvod', 'Výroba', 'Technologie', 'Strojový park', 'Certifikace', 'Reference', 'Kariéra', 'Poptávka'],
  features=['Formulář s nahráním výkresů', 'Jazykové verze', 'Kariérní stránka'],
  seo=['„CNC obrábění + region“, „frézování na zakázku“', 'Stránky technologií', 'Vícejazyčné SEO'],
  faq=[('Proč potřebuje výrobní firma moderní web?', 'Kvůli novým odběratelům a náboru. Nákupčí i uchazeči si firmu vždy ověří na webu.'),
       ('Máte zkušenosti s výrobními firmami?', 'Ano – podívejte se na naši referenci KONRADT (CNC obrábění, montáže a odlitky).')]),
dict(slug='obchod-drevo', name='Web pro obchod se dřevem a pilu', short='obchod se dřevem / pila', group='Výroba a B2B', ref='brincil',
  problem='Zákazníci hledají palivové dřevo, řezivo nebo kulatinu podle ceny, dostupnosti a dopravy. Pila nebo obchod se dřevem bez aktuálního ceníku a objednávky ztrácí zakázky.',
  must=['Sortiment (palivové dřevo, řezivo, kulatina, štěpka)', 'Aktuální ceník', 'Doprava a rozvoz', 'Objednávkový formulář', 'Výkup dřeva', 'Technika a kapacity', 'Fotky provozu', 'Kontakt'],
  pages=['Úvod', 'Palivové dřevo', 'Řezivo', 'Ceník', 'Doprava', 'Výkup', 'Kontakt'],
  features=['Objednávkový formulář', 'Kalkulace dopravy', 'Google profil'],
  seo=['„Palivové dřevo + region“, „řezivo + město“', 'Sezónní obsah', 'Ceník'],
  faq=[('Kdy je největší poptávka po palivovém dřevě?', 'Na podzim. Web s ceníkem a objednávkou je potřeba mít připravený už v létě.'),
       ('Máte zkušenosti s tímto oborem?', 'Ano – podívejte se na naši referenci Břinčil (obchod se dřevem a řezivem).')]),
dict(slug='dopravce', name='Web pro dopravní a logistickou firmu', short='dopravce', group='Výroba a B2B',
  problem='Zákazníci hledají dopravce podle typu nákladu, trasy a kapacity. Web dopravce často neříká nic konkrétního – a přitom potřebuje sbírat poptávky přeprav i řidiče.',
  must=['Typy přeprav (vnitrostátní, mezinárodní, nadrozměr)', 'Vozový park s parametry', 'Trasy a regiony', 'Poptávka přepravy', 'Certifikace a pojištění', 'Kariéra – nábor řidičů', 'Reference', 'Kontakt'],
  pages=['Úvod', 'Služby', 'Vozový park', 'Poptávka přepravy', 'Kariéra', 'Kontakt'],
  features=['Poptávkový formulář', 'Kariérní stránka', 'Jazykové verze'],
  seo=['„Autodoprava + region“, „mezinárodní přeprava“', 'Nábor řidičů', 'Jazykové verze'],
  faq=[('Pomůže web s náborem řidičů?', 'Ano – samostatná kariérní stránka s podmínkami a jednoduchým formulářem přivede uchazeče mnohem lépe než inzerát.'),
       ('Je potřeba jazyková verze?', 'Pro mezinárodní dopravu určitě – minimálně angličtina a němčina.')]),
# ---------------- Komunita a veřejný sektor ----------------
dict(slug='obec', name='Web pro obec', short='obec', group='Komunita a veřejný sektor',
  problem='Obecní weby bývají zastaralé, nepřehledné a nesplňují přístupnost. Občané přitom chtějí rychle najít úřední hodiny, aktuality, formuláře a úřední desku – i z mobilu.',
  must=['Úřední deska', 'Aktuality a hlášení rozhlasu', 'Úřední hodiny a kontakty', 'Formuláře a poplatky', 'Zastupitelstvo, vyhlášky, rozpočet', 'Kalendář akcí', 'Turistické informace', 'Přístupnost podle zákona'],
  pages=['Úvod', 'Obecní úřad', 'Úřední deska', 'Aktuality', 'Samospráva', 'Pro občany', 'Turistika', 'Kontakt'],
  features=['Napojení úřední desky', 'SMS/e-mail hlášení', 'Přístupnost (WCAG)', 'Kalendář akcí'],
  seo=['Turistický obsah přivádí návštěvníky obce', 'Přehledná struktura pro občany', 'Rychlost na mobilu'],
  faq=[('Splní web obce zákon o přístupnosti?', 'Ano – web postavíme podle požadavků na přístupnost a připravíme prohlášení o přístupnosti.'),
       ('Může si obec web spravovat sama?', 'Ano, aktuality, úřední desku i akce zvládne kdokoli z úřadu bez technických znalostí.')]),
dict(slug='spolek', name='Web pro spolek a neziskovou organizaci', short='spolek / nezisková organizace', group='Komunita a veřejný sektor',
  problem='Spolky žijí z dobrovolníků, členů a dárců. Web musí ukázat, co děláte, přilákat nové lidi a umožnit podpořit vás – jinak zůstane jen u Facebooku, kde vás nenajdou noví zájemci.',
  must=['Poslání a činnost', 'Akce a kalendář', 'Jak se zapojit / členství', 'Darování online', 'Výroční zprávy a transparentnost', 'Partneři a podporovatelé', 'Fotogalerie', 'Kontakt'],
  pages=['Úvod', 'O nás', 'Činnost', 'Akce', 'Zapojte se', 'Podpořte nás', 'Kontakt'],
  features=['Online dary', 'Kalendář akcí', 'Přihlášky'],
  seo=['Obsah o činnosti a regionu', 'Akce s datem a místem', 'Odkazy od partnerů'],
  faq=[('Jde na webu přijímat dary?', 'Ano – online platbou nebo QR kódem pro bankovní převod, včetně potvrzení o daru.'),
       ('Kolik stojí web pro spolek?', 'Jednoduchý web začíná na 9 900 Kč. Rádi probereme i možnosti pro neziskové organizace.')]),
dict(slug='sportovni-klub', name='Web pro sportovní klub', short='sportovní klub', group='Komunita a veřejný sektor',
  problem='Rodiče hledají, kam dát dítě na sport, a fanoušci chtějí výsledky. Klubový web často ani jedno nezvládá – rozpisy jsou v PDF a přihláška v e-mailu.',
  must=['Týmy a kategorie', 'Rozpisy zápasů a výsledky', 'Nábor nových členů s přihláškou', 'Tréninky a kontakty na trenéry', 'Aktuality a fotky', 'Partneři a sponzoři', 'Členské příspěvky', 'Kontakt a areál'],
  pages=['Úvod', 'Týmy', 'Zápasy a výsledky', 'Nábor', 'Aktuality', 'Partneři', 'Kontakt'],
  features=['Online přihláška', 'Platba příspěvků', 'Napojení na svazové výsledky'],
  seo=['„Nábor + sport + město“', 'Aktuality s fotkami', 'Stránky týmů'],
  faq=[('Jde napojit výsledky ze svazového systému?', 'U řady sportů ano – výsledky a tabulky se pak aktualizují samy.'),
       ('Pomůže web náboru dětí?', 'Výrazně – rodiče hledají „fotbal pro děti + město“ a jasná přihláška rozhoduje.')]),
dict(slug='hasici', name='Web pro sbor dobrovolných hasičů', short='SDH / hasiči', group='Komunita a veřejný sektor',
  problem='Hasičské sbory dělají spoustu práce pro obec, ale na webu to často není vidět. Web pomůže s náborem mladých hasičů, prezentací zásahů a podporou od sponzorů.',
  must=['Výjezdy a zásahy', 'Mladí hasiči a nábor', 'Soutěže a výsledky', 'Akce pro veřejnost', 'Technika', 'Historie sboru', 'Sponzoři', 'Kontakt'],
  pages=['Úvod', 'Zásahy', 'Mladí hasiči', 'Soutěže', 'Akce', 'Technika', 'Kontakt'],
  features=['Aktuality', 'Fotogalerie', 'Kalendář akcí'],
  seo=['Obsah o akcích a soutěžích', 'Nábor mladých hasičů', 'Odkazy z webu obce'],
  faq=[('Kdo bude web aktualizovat?', 'Kdokoli ze sboru – přidat aktualitu s fotkami zvládne z mobilu za pár minut.'),
       ('Je web pro hasiče drahý?', 'Ne – jednoduchý web s aktualitami a galerií patří k nejlevnějším řešením.')]),
dict(slug='materska-skola', name='Web pro mateřskou školu', short='mateřská škola', group='Komunita a veřejný sektor',
  problem='Rodiče chtějí na webu školky najít jídelníček, informace o zápisu, akce a důležité dokumenty. Starý web s neaktuálními informacemi způsobuje hromadu telefonátů.',
  must=['Zápis – termíny a dokumenty', 'Jídelníček', 'Akce a fotogalerie', 'Třídy a pedagogové', 'Školní vzdělávací program', 'Úřední dokumenty a přístupnost', 'Platby (školné, stravné)', 'Kontakt'],
  pages=['Úvod', 'O školce', 'Zápis', 'Jídelníček', 'Akce', 'Dokumenty', 'Kontakt'],
  features=['Jednoduchá správa jídelníčku', 'Zabezpečená galerie pro rodiče', 'Přístupnost'],
  seo=['„Mateřská škola + obec“, „zápis do MŠ + obec“', 'Aktuální informace', 'Přístupnost'],
  faq=[('Jak chránit fotky dětí na webu?', 'Fotogalerii zabezpečíme heslem jen pro rodiče a zveřejňujeme jen se souhlasem.'),
       ('Splní web povinnou přístupnost?', 'Ano – postavíme ho podle požadavků na přístupnost webů veřejného sektoru.')]),
dict(slug='skola', name='Web pro základní a střední školu', short='škola', group='Komunita a veřejný sektor',
  problem='Školní web slouží rodičům, žákům i uchazečům. Často je ale přeplněný, zastaralý a na mobilu nepoužitelný – a přitom rozhoduje o tom, kam se přihlásí noví žáci.',
  must=['Informace pro uchazeče a přijímací řízení', 'Aktuality a akce', 'Rozvrhy a suplování', 'Školní jídelna', 'Kontakty na pedagogy', 'Úřední dokumenty', 'Přístupnost', 'Fotogalerie'],
  pages=['Úvod', 'Pro uchazeče', 'Pro rodiče', 'Pro žáky', 'Aktuality', 'Dokumenty', 'Kontakt'],
  features=['Napojení na školní systémy', 'Přístupnost', 'Aktuality'],
  seo=['„Škola + obor + město“ pro uchazeče', 'Dny otevřených dveří', 'Přehledná struktura'],
  faq=[('Jde napojit suplování a rozvrhy?', 'Ve většině případů ano – odkazem nebo vložením ze školního informačního systému.'),
       ('Pomůže web s náborem žáků?', 'Ano – stránka pro uchazeče s obory, přijímačkami a dny otevřených dveří je pro rodiče klíčová.')]),
dict(slug='svj', name='Web pro SVJ a bytové družstvo', short='SVJ / bytové družstvo', group='Komunita a veřejný sektor',
  problem='Vlastníci bytů potřebují mít přehled o shromážděních, dokumentech, opravách a kontaktech. Nástěnka v chodbě a e-maily nestačí – web SVJ ušetří výboru spoustu práce.',
  must=['Aktuality a oznámení', 'Dokumenty (stanovy, zápisy, rozpočet) – zabezpečené', 'Kontakty na výbor a správce', 'Hlášení závad', 'Kalendář shromáždění', 'Domovní řád', 'Úklid a revize', 'Kontakt'],
  pages=['Úvod', 'Aktuality', 'Dokumenty (pro členy)', 'Hlášení závad', 'Kontakty'],
  features=['Zabezpečená sekce pro vlastníky', 'Formulář hlášení závad', 'Rozesílání oznámení'],
  seo=['Web SVJ obvykle nemusí být vidět ve vyhledávání – důležitá je přehlednost a zabezpečení'],
  faq=[('Jak zabezpečit dokumenty jen pro vlastníky?', 'Přihlášením nebo heslem – veřejná zůstane jen základní stránka s kontakty.'),
       ('Kolik stojí web pro SVJ?', 'Jednoduchý web s dokumenty a hlášením závad patří k levnějším řešením – rádi pošleme nabídku.')]),
dict(slug='farnost', name='Web pro farnost', short='farnost', group='Komunita a veřejný sektor',
  problem='Farníci chtějí vědět, kdy jsou bohoslužby, a turisté hledají otevírací dobu kostela. Farnost bez aktuálního webu odpovídá stále na stejné otázky.',
  must=['Pořad bohoslužeb', 'Ohlášky', 'Svátosti – křty, svatby, pohřby', 'Akce farnosti', 'Kontakt na kněze a kancelář', 'Historie kostela', 'Turistické informace', 'Dary'],
  pages=['Úvod', 'Bohoslužby', 'Ohlášky', 'Svátosti', 'Akce', 'Kostel', 'Kontakt'],
  features=['Snadná úprava ohlášek', 'Kalendář', 'Online dary'],
  seo=['Historie kostela a turistické informace', 'Aktuální bohoslužby', 'Odkazy z webu obce'],
  faq=[('Kdo bude upravovat ohlášky?', 'Kdokoli z farnosti – je to stejně snadné jako napsat e-mail.'),
       ('Jde přijímat dary online?', 'Ano – bankovním převodem s QR kódem nebo platbou kartou.')]),
# ---------------- Ostatní ----------------
dict(slug='farma', name='Web pro farmu a farmářský obchod', short='farma', group='Ostatní',
  problem='Lidé chtějí kupovat lokálně a přímo od farmáře – ale potřebují vědět, co máte, kdy a kde. Farma bez webu a objednávek prodává jen těm, kdo ji náhodou znají.',
  must=['Co produkujete a kdy (sezónnost)', 'Ceník a objednávky / bedýnky', 'Prodejní místa a výdejní dny', 'Příběh farmy a způsob chovu', 'Fotky zvířat a polí', 'Exkurze a akce', 'Velkoodběr pro restaurace', 'Kontakt'],
  pages=['Úvod', 'Naše produkty', 'Objednávka', 'Kde nás koupíte', 'O farmě', 'Akce', 'Kontakt'],
  features=['Jednoduchý e-shop s výdejními dny', 'Předplatné bedýnek', 'Newsletter'],
  seo=['„Farma + region“, „farmářské maso + město“', 'Sezónní obsah', 'Příběh farmy'],
  faq=[('Jde prodávat bedýnky přes web?', 'Ano – i předplatné s pravidelným výdejem. Zákazník si objedná a zaplatí online.'),
       ('Potřebuje farma e-shop?', 'Pokud prodáváte víc produktů, ano. Jinak stačí objednávkový formulář a výdejní dny.')]),
dict(slug='vinarstvi', name='Web pro vinařství', short='vinařství', group='Ostatní',
  problem='Vinařství prodává víno, zážitky i příběh. Web často ukáže jen etikety – a přitom může prodávat online, plnit degustace a ubytování.',
  must=['E-shop s víny a ověřením věku', 'Degustace a jejich rezervace', 'Příběh vinařství a vinice', 'Ocenění', 'Ubytování / sklípek', 'Akce (otevřené sklepy)', 'Velkoodběr pro restaurace', 'Kontakt'],
  pages=['Úvod', 'Vína (e-shop)', 'Degustace', 'Vinařství', 'Ubytování', 'Akce', 'Kontakt'],
  features=['E-shop', 'Rezervace degustací', 'Newsletter'],
  seo=['„Vinařství + oblast“, „degustace vína + region“', 'Stránky odrůd', 'Akce'],
  faq=[('Je e-shop s vínem složitý?', 'Ne – stačí ověření věku a správné nastavení dopravy. Rádi poradíme i s legislativou.'),
       ('Jak naplnit degustace?', 'Online rezervací s výběrem termínu a dárkovými poukazy.')]),
dict(slug='vcelar', name='Web pro včelaře a prodej medu', short='včelař', group='Ostatní',
  problem='Poctivý med se prodává sám – když o něm lidé vědí. Včelař bez webu prodává jen sousedům, přitom zájem o lokální med je velký.',
  must=['Druhy medu a ceník', 'Objednávka a výdejní místa', 'Příběh včelaře a stanoviště', 'Dárková balení', 'Další produkty (propolis, svíčky)', 'Kvalita a rozbory', 'Fotky', 'Kontakt'],
  pages=['Úvod', 'Med a produkty', 'Objednávka', 'O nás', 'Kontakt'],
  features=['Jednoduchý e-shop', 'Dárková balení', 'Google profil'],
  seo=['„Med od včelaře + region“', 'Obsah o druzích medu', 'Dárková balení'],
  faq=[('Stačí jednostránkový web?', 'Ano – produkty, příběh, objednávka a kontakt na jedné stránce plně stačí.'),
       ('Jde med posílat?', 'Ano, s vhodným balením – napojíme dopravce a platby.')]),
dict(slug='chovatelska-stanice', name='Web pro chovatelskou stanici', short='chovatelská stanice', group='Ostatní',
  problem='Zájemci o štěně nebo kotě hledají seriózního chovatele. Web musí ukázat rodiče, zdraví, plánované vrhy a přístup – a odfiltrovat nevhodné zájemce.',
  must=['Plemeno a chovatelská filozofie', 'Chovní jedinci s výsledky a zdravím', 'Plánované a aktuální vrhy', 'Odchovy a jejich noví majitelé', 'Podmínky prodeje', 'Formulář pro zájemce', 'Fotky a videa', 'Kontakt'],
  pages=['Úvod', 'Naši psi / kočky', 'Vrhy', 'Odchovy', 'Pro zájemce', 'Kontakt'],
  features=['Formulář pro zájemce', 'Galerie', 'Aktuality'],
  seo=['„Chovatelská stanice + plemeno“', 'Aktuální vrhy', 'Obsah o plemeni'],
  faq=[('Jak odfiltrovat nevhodné zájemce?', 'Podrobným formulářem s otázkami na zkušenosti a podmínky – ušetříte čas a najdete správné majitele.'),
       ('Kolik stránek potřebuji?', 'Obvykle 5–10, podle počtu chovných jedinců a vrhů.')]),
dict(slug='psi-salon', name='Web pro psí salon a hotel pro psy', short='psí salon / hotel pro psy', group='Ostatní',
  problem='Majitelé svěřují psa jen tomu, komu důvěřují. Web musí ukázat prostředí, péči a ceny – a umožnit rezervaci, hlavně před prázdninami.',
  must=['Služby (střihání, koupání, trimování, hlídání)', 'Ceník podle velikosti a plemene', 'Online rezervace', 'Fotky prostředí a „před a po“', 'Podmínky pobytu (očkování)', 'Recenze', 'Kontakt', 'Otevírací doba'],
  pages=['Úvod', 'Služby', 'Ceník', 'Rezervace', 'Galerie', 'Kontakt'],
  features=['Rezervační systém', 'Google recenze', 'Instagram'],
  seo=['„Psí salon + město“, „hlídání psů + město“', 'Sezónní obsah (prázdniny)', 'Recenze'],
  faq=[('Dá se rezervovat hlídání přes web?', 'Ano, s kalendářem kapacity – nehrozí přeplnění v sezóně.'),
       ('Co nejvíc pomáhá důvěře?', 'Fotky prostředí, recenze a jasné podmínky. Majitel musí vědět, kam psa dává.')]),
dict(slug='pohrebni-sluzba', name='Web pro pohřební službu', short='pohřební služba', group='Ostatní',
  problem='Pozůstalí hledají pomoc v těžké chvíli a často v noci. Web musí být klidný, srozumitelný a hned nabídnout nonstop kontakt a jasný postup.',
  must=['Nonstop telefon na viditelném místě', 'Co dělat, když někdo zemře – krok za krokem', 'Služby a typy pohřbů', 'Ceník', 'Smuteční oznámení', 'Smuteční vazby', 'Kontakt a pobočky', 'Citlivý design'],
  pages=['Úvod', 'Co dělat při úmrtí', 'Služby', 'Ceník', 'Smuteční oznámení', 'Kontakt'],
  features=['Tlačítko nonstop volání', 'Formulář pro smuteční oznámení', 'Google profil'],
  seo=['„Pohřební služba + město“', 'Návod „co dělat při úmrtí“ je nejhledanější obsah', 'Ceník'],
  faq=[('Má pohřební služba uvádět ceny?', 'Ano – pozůstalí oceňují transparentnost a méně se musí vyptávat v těžké chvíli.'),
       ('Jaký tón by měl web mít?', 'Klidný, důstojný a praktický. Bez agresivních výzev, s jasnými informacemi.')]),
dict(slug='osobni-web', name='Osobní web a portfolio', short='osobní web / portfolio', group='Ostatní',
  problem='Freelanceři, kreativci i odborníci často spoléhají jen na LinkedIn nebo Instagram. Vlastní web je místo, které patří vám, buduje osobní značku a přivádí zakázky bez prostředníků.',
  must=['Kdo jste a co nabízíte – jasně v první větě', 'Portfolio nebo případové studie', 'Služby a ceny', 'Reference', 'O mně', 'Kontakt / rezervace konzultace', 'Blog nebo myšlenky', 'Odkazy na sítě'],
  pages=['Úvod', 'Portfolio', 'Služby', 'O mně', 'Blog', 'Kontakt'],
  features=['Rezervace konzultací', 'Newsletter', 'Vlastní doména'],
  seo=['Optimalizace na jméno a obor', 'Blog s odbornými tématy', 'Odkazy z profilů'],
  faq=[('Potřebuji osobní web, když mám LinkedIn?', 'LinkedIn vám nepatří a nepřivede klienty z Googlu. Osobní web je vaše vizitka, kterou máte pod kontrolou.'),
       ('Kolik stránek má osobní web?', 'Obvykle 3–8. Často stačí jednostránkový web s kvalitním portfoliem.')]),
dict(slug='umelec-muzikant', name='Web pro umělce a muzikanta', short='umělec / muzikant', group='Ostatní',
  problem='Umělci potřebují ukázat tvorbu, termíny vystoupení a dát se kontaktovat pořadatelům. Rozházené odkazy po sociálních sítích pořadatele nepřesvědčí.',
  must=['Ukázky tvorby (audio, video, galerie)', 'Kalendář vystoupení / výstav', 'Biografie', 'Press kit ke stažení', 'Kontakt pro pořadatele a booking', 'Prodej děl nebo merche', 'Newsletter', 'Odkazy na platformy'],
  pages=['Úvod', 'Tvorba', 'Koncerty / výstavy', 'Bio', 'Press kit', 'Shop', 'Kontakt'],
  features=['Audio a video přehrávač', 'Kalendář akcí', 'Malý e-shop'],
  seo=['Optimalizace na jméno umělce', 'Akce s místem a datem', 'Rozhovory a recenze'],
  faq=[('Co je press kit a proč ho mít na webu?', 'Balíček fotek, bia a technických informací pro pořadatele a média. Ušetří vám desítky e-mailů.'),
       ('Jde prodávat obrazy nebo merch?', 'Ano – i jednoduchý e-shop s pár položkami a online platbou.')]),
]
