"""Oborové landing pages – část A: krása a zdraví, ubytování a gastro.
Pole: slug, name (Web pro …), short (název oboru do textu), group, problem, must (co musí mít), pages (struktura webu),
features (funkce/napojení), seo (tipy), faq [(otázka, odpověď)], ref (volitelně klíč reference)."""

A = [
# ---------------- Krása a zdraví ----------------
dict(slug='kadernictvi', name='Web pro kadeřnictví', short='kadeřnictví', group='Krása a zdraví',
  problem='Většina kadeřnictví má buď jen profil na Facebooku, nebo web, kde chybí ceník a možnost objednat se. Zákaznice pak volají v nejnevhodnější chvíli – když stříháte – nebo jdou ke konkurenci, kde si termín zarezervují jedním klikem v noci z gauče.',
  must=['Online rezervace termínů napojená na kalendář', 'Přehledný ceník podle délky vlasů a typu služby', 'Galerie proměn „před a po“', 'Představení týmu a specializací jednotlivých stylistů', 'Recenze z Googlu přímo na webu', 'Otevírací doba, mapa a parkování', 'Odkaz na Instagram s ukázkami prací', 'Prodej dárkových poukazů'],
  pages=['Úvod', 'Služby a ceník', 'Online rezervace', 'Galerie prací', 'Náš tým', 'Dárkové poukazy', 'Kontakt'],
  features=['Rezervační systém (Reservio, Bookio nebo vlastní)', 'Napojení na Instagram', 'Google Firemní profil a recenze', 'SMS/e-mail připomínky termínů'],
  seo=['Optimalizace na „kadeřnictví + město“ a konkrétní služby (balayage, melír, svatební účesy)', 'Pravidelně přidávané fotky prací s popisky', 'Sbírání recenzí po každé návštěvě'],
  faq=[('Potřebuje kadeřnictví vlastní web, když má Instagram?', 'Instagram je výborná výloha, ale nenajde vás přes Google a nejde se přes něj pohodlně objednat. Web s rezervací a ceníkem pracuje i ve chvíli, kdy stříháte a nemůžete brát telefon.'),
       ('Kolik stojí web pro kadeřnictví?', 'Jednodušší web s ceníkem, galerií a napojením na rezervační systém začíná na 9 900 Kč. Přesnou cenu ovlivní hlavně počet stránek a typ rezervací.')]),
dict(slug='barbershop', name='Web pro barbershop', short='barbershop', group='Krása a zdraví',
  problem='Barbershop žije stylem a komunitou – jenže web často působí jako šablona z roku 2010. Klienti chtějí vidět atmosféru, holiče a hlavně si rovnou vybrat volný termín, ideálně u svého oblíbeného barbera.',
  must=['Rezervace podle konkrétního barbera', 'Ceník střihů, úprav vousů a kombinací', 'Fotky prací a atmosféry podniku', 'Profily barberů s jejich styly', 'Prodej produktů nebo dárkových poukazů', 'Věrnostní program nebo permanentky', 'Mapa, otevírací doba a parkování', 'Recenze klientů'],
  pages=['Úvod', 'Služby a ceník', 'Rezervace', 'Barbeři', 'Galerie', 'Shop / poukazy', 'Kontakt'],
  features=['Rezervace s výběrem barbera', 'Napojení na Instagram a TikTok', 'Jednoduchý e-shop s kosmetikou', 'Google recenze'],
  seo=['Cílení na „barbershop + město“ i „pánský střih + město“', 'Obsah o službách (fade, úprava vousů, hot towel)', 'Lokální odkazy a recenze'],
  faq=[('Jde napojit rezervace přímo na kalendář barberů?', 'Ano. Každý barber může mít vlastní kalendář a klient si vybere, ke komu chce jít. Napojíme běžné rezervační systémy nebo připravíme vlastní řešení.'),
       ('Dá se na webu prodávat kosmetika?', 'Ano, i malý e-shop s pár produkty pro vousy a vlasy. Často se vyplatí kombinovat s dárkovými poukazy.')]),
dict(slug='kosmeticky-salon', name='Web pro kosmetický salon', short='kosmetický salon', group='Krása a zdraví',
  problem='Klientky kosmetiky se rozhodují podle důvěry – chtějí vidět prostředí, vědět, jaké ošetření je pro ně vhodné, a znát cenu dopředu. Web, který jen vyjmenuje služby bez vysvětlení a cen, je pošle jinam.',
  must=['Popis ošetření – pro koho jsou, jak probíhají, jak dlouho trvají', 'Ceník včetně balíčků a permanentek', 'Online rezervace', 'Fotky salonu a výsledků (se souhlasem klientek)', 'Informace o používané kosmetice a značkách', 'Dárkové poukazy online', 'Recenze a reference', 'Kontakt, mapa, otevírací doba'],
  pages=['Úvod', 'Ošetření (podstránka pro každé)', 'Ceník', 'Rezervace', 'O salonu', 'Dárkové poukazy', 'Blog / péče o pleť', 'Kontakt'],
  features=['Rezervační systém', 'Prodej poukazů s online platbou', 'Newsletter pro stálé klientky', 'Google Firemní profil'],
  seo=['Samostatné stránky pro hlavní ošetření (např. „hydrafacial + město“)', 'Články o péči o pleť přivádějí nové klientky', 'Recenze s konkrétními ošetřeními'],
  faq=[('Má smysl dělat stránku pro každé ošetření?', 'Ano. Lidé hledají konkrétní ošetření a samostatná stránka s popisem, cenou a fotkami má mnohem větší šanci se zobrazit ve vyhledávání.'),
       ('Můžu prodávat dárkové poukazy online?', 'Ano. Klient zaplatí kartou a poukaz mu automaticky přijde e-mailem – ideální před Vánoci a Valentýnem.')]),
dict(slug='nehtove-studio', name='Web pro nehtové studio', short='nehtové studio', group='Krása a zdraví',
  problem='Nehtové studio prodává hlavně vizuálem. Když web neukazuje aktuální práce a nejde přes něj rezervovat, klientky zůstanou u Instagramu – a tam vás najdou jen ti, kdo vás už znají.',
  must=['Galerie prací rozdělená podle stylu', 'Ceník (gel, akryl, manikúra, pedikúra, doplatky)', 'Online rezervace', 'Informace o hygieně a materiálech', 'Recenze klientek', 'Napojení na Instagram', 'Dárkové poukazy', 'Kontakt a mapa'],
  pages=['Úvod', 'Služby a ceník', 'Galerie', 'Rezervace', 'O mně', 'Kontakt'],
  features=['Rezervace s délkou služby', 'Instagram feed na webu', 'Google recenze'],
  seo=['Cílení na „nehtové studio + město“, „gelové nehty + město“', 'Popisky fotek s názvy technik', 'Recenze s fotkami'],
  faq=[('Stačí jednostránkový web?', 'Pro začínající studio ano – úvod, ceník, galerie, rezervace a kontakt na jedné stránce. Později se dá rozšířit.'),
       ('Jak dostanu na web fotky z Instagramu?', 'Napojíme Instagram feed, takže se nové fotky na webu objeví automaticky.')]),
dict(slug='masaze', name='Web pro masáže a wellness', short='masážní salon', group='Krása a zdraví',
  problem='Klienti masáží hledají klid a důvěru. Pokud z webu nepoznají, jaký typ masáže je pro ně vhodný, kolik stojí a kdy je volno, raději nezavolají vůbec.',
  must=['Přehled masáží s popisem účinků a délky', 'Ceník a balíčky', 'Online rezervace volných termínů', 'Fotky prostředí', 'Informace o maserovi/terapeutovi a kvalifikaci', 'Dárkové poukazy online', 'Kontraindikace a FAQ', 'Kontakt a parkování'],
  pages=['Úvod', 'Masáže', 'Ceník', 'Rezervace', 'O mně', 'Poukazy', 'Kontakt'],
  features=['Rezervační kalendář', 'Online prodej poukazů', 'Google recenze'],
  seo=['Stránky pro jednotlivé typy masáží', '„Masáže + město“ a „dárkový poukaz na masáž + město“', 'Sezónní obsah (Vánoce, Den matek)'],
  faq=[('Prodají se poukazy na masáž přes web?', 'Velmi dobře – hlavně před svátky. Online platba a automatické zaslání poukazu ušetří spoustu telefonování.'),
       ('Musím mít rezervační systém?', 'Nemusíte, ale klienti si dnes rádi vybírají termín sami. Ušetří vám to čas i zmeškané hovory.')]),
dict(slug='tetovaci-studio', name='Web pro tetovací studio', short='tetovací studio', group='Krása a zdraví',
  problem='Tetování je osobní rozhodnutí na celý život. Klient chce vidět portfolio tatéra, jeho styl a vědět, jak probíhá konzultace. Web, který tohle neukáže, nedokáže převést zájem v objednávku.',
  must=['Portfolio každého tatéra zvlášť', 'Styly, ve kterých studio tetuje', 'Formulář pro návrh – popis motivu, místo, velikost, reference', 'Orientační ceny nebo princip nacenění', 'Péče o tetování po zákroku', 'Hygiena a certifikace', 'Volné termíny / guest spoty', 'Kontakt'],
  pages=['Úvod', 'Tatéři a portfolia', 'Objednávka návrhu', 'Ceny a záloha', 'Péče o tetování', 'FAQ', 'Kontakt'],
  features=['Formulář s nahráním referenčních obrázků', 'Platba zálohy online', 'Instagram'],
  seo=['„Tetovací studio + město“ a jednotlivé styly (fineline, realismus)', 'Článek o péči o tetování přivádí návštěvy', 'Portfolio s popisky'],
  faq=[('Jde přes web vybírat zálohy?', 'Ano, platbu zálohy kartou umíme napojit na objednávkový formulář – omezí to nedorazivší klienty.'),
       ('Jak řešit víc tatérů v jednom studiu?', 'Každý tatér má vlastní profil s portfoliem a klient si vybere, ke komu chce jít.')]),
dict(slug='fyzioterapie', name='Web pro fyzioterapii', short='fyzioterapie', group='Krása a zdraví',
  problem='Pacienti hledají fyzioterapeuta s konkrétním problémem – bolest zad, rehabilitace po úrazu, sportovní zranění. Když web mluví obecně a nejde se objednat, odejdou ke konkurenci.',
  must=['Popis potíží, se kterými pomáháte', 'Metody a techniky (s vysvětlením pro laiky)', 'Ceník – samoplátci i pojišťovny', 'Online objednání', 'Profil terapeuta, vzdělání a certifikace', 'Co si vzít s sebou na první návštěvu', 'Recenze pacientů', 'Kontakt, mapa, bezbariérovost'],
  pages=['Úvod', 'S čím pomáhám', 'Metody', 'Ceník', 'Objednání', 'O mně', 'Kontakt'],
  features=['Rezervační systém', 'Formulář s popisem potíží', 'Google recenze'],
  seo=['Stránky pro konkrétní potíže (bolest zad, krční páteř…)', '„Fyzioterapie + město“', 'Odborné články s praktickými cviky'],
  faq=[('Má smysl psát na web o konkrétních diagnózách?', 'Ano, lidé hledají přesně svůj problém. Stránka „bolest zad – fyzioterapie v Jeseníku“ přivede pacienta mnohem spolehlivěji než obecný úvod.'),
       ('Jak řešit pojišťovny a samoplátce?', 'Přehledně v ceníku a v FAQ – pacient hned ví, co hradí pojišťovna a co platí sám.')]),
dict(slug='zubni-ordinace', name='Web pro zubní ordinaci', short='zubní ordinace', group='Krása a zdraví',
  problem='Pacienti dnes hledají zubaře hlavně podle toho, jestli přijímá nové pacienty a co nabízí. Ordinace s neaktuálním webem zbytečně odpovídá na stejné dotazy po telefonu.',
  must=['Jasná informace, zda přijímáte nové pacienty', 'Ordinační hodiny a akutní ošetření', 'Služby (preventivní péče, dentální hygiena, implantáty, estetika)', 'Ceník nadstandardních výkonů', 'Smluvní pojišťovny', 'Tým a vybavení ordinace', 'Online objednání nebo formulář', 'Kontakt, mapa, bezbariérovost'],
  pages=['Úvod', 'Služby', 'Ceník', 'Pro nové pacienty', 'Tým', 'Objednání', 'Kontakt'],
  features=['Objednávkový formulář', 'Informační lišta (dovolená, změny)', 'Google Firemní profil'],
  seo=['„Zubař + město“, „dentální hygiena + město“', 'Stránky pro jednotlivé výkony', 'Aktuální informace o přijímání pacientů'],
  faq=[('Jak na webu řešit, že nepřijímáme nové pacienty?', 'Jasnou informací na úvodní stránce a v kontaktu – ušetří vám to desítky telefonátů týdně. Kdykoli ji změníte sami.'),
       ('Musí mít ordinace na webu ceník?', 'Pro nadstandardní výkony je to velmi vhodné – pacienti oceňují transparentnost a méně se ptají po telefonu.')]),
dict(slug='veterina', name='Web pro veterinární ordinaci', short='veterina', group='Krása a zdraví',
  problem='Majitel zvířete hledá veterináře často ve stresu – potřebuje okamžitě vědět ordinační hodiny, pohotovost a jestli ho vezmete. Nepřehledný web v tu chvíli prohrává.',
  must=['Ordinační hodiny a pohotovost na viditelném místě', 'Služby (prevence, očkování, chirurgie, stomatologie…)', 'Jaká zvířata ošetřujete', 'Objednávání', 'Tým veterinářů', 'Ceník základních úkonů', 'Rady pro majitele', 'Kontakt, mapa, parkování'],
  pages=['Úvod', 'Služby', 'Pohotovost', 'Objednání', 'Tým', 'Rady pro majitele', 'Kontakt'],
  features=['Lišta s aktuálními informacemi', 'Objednávkový formulář', 'Google recenze'],
  seo=['„Veterina + město“, „pohotovost veterina + region“', 'Články o očkování a prevenci', 'Aktuální ordinační hodiny v Google profilu'],
  faq=[('Jak zvýraznit pohotovost?', 'Výraznou lištou nebo tlačítkem s telefonem v hlavičce na všech stránkách – na mobilu na jeden klik.'),
       ('Mají veterinární ordinace na webu ceník?', 'Základní úkony (očkování, čipování, kastrace) ano – majitelé to ocení a ušetříte čas.')]),
dict(slug='psycholog', name='Web pro psychologa a terapeuta', short='psychologická praxe', group='Krása a zdraví',
  problem='Člověk, který hledá terapii, potřebuje důvěru a bezpečí. Web musí být klidný, srozumitelný a citlivý – a zároveň jasně říct, s čím pomáháte, kolik to stojí a jak se objednat.',
  must=['S čím pomáháte (úzkosti, vztahy, vyhoření…)', 'Přístup a směr terapie srozumitelně', 'Vzdělání, výcvik a supervize', 'Cena a délka sezení', 'Možnost online terapie', 'Jak probíhá první setkání', 'Diskrétní kontaktní formulář', 'Informace o ochraně dat'],
  pages=['Úvod', 'S čím pomáhám', 'Jak pracuji', 'O mně', 'Cena', 'Objednání', 'Kontakt'],
  features=['Rezervace konzultací', 'Online platby', 'Bezpečný formulář'],
  seo=['„Psycholog + město“, „terapie online“', 'Odborné články na běžná témata', 'Jasné odpovědi v FAQ'],
  faq=[('Jak zajistit diskrétnost na webu?', 'Formulář bez zbytečných údajů, zabezpečený přenos a jasné informace o ochraně dat. Nesdílíme nic s reklamními sítěmi bez souhlasu.'),
       ('Má smysl nabízet na webu online terapii?', 'Ano – rozšíří to okruh klientů daleko za vaše město.')]),
dict(slug='optika', name='Web pro oční optiku', short='oční optika', group='Krása a zdraví',
  problem='Optika soutěží s velkými řetězci a e-shopy. Vyhrává osobním přístupem – ale ten musí být vidět už na webu: měření zraku, výběr obrub, servis a značky, které nabízíte.',
  must=['Měření zraku a objednání termínu', 'Značky obrub a brýlových čoček', 'Kontaktní čočky a příslušenství', 'Servis a opravy', 'Akce a slevy', 'Tým a odbornost', 'Otevírací doba a mapa', 'Recenze'],
  pages=['Úvod', 'Měření zraku', 'Brýle a obruby', 'Kontaktní čočky', 'Servis', 'Akce', 'Kontakt'],
  features=['Objednání měření', 'Katalog značek', 'Google Firemní profil'],
  seo=['„Oční optika + město“, „měření zraku + město“', 'Obsah o značkách obrub', 'Sezónní akce'],
  faq=[('Potřebuje optika e-shop?', 'Často stačí katalog a objednání měření – brýle si lidé chtějí vyzkoušet. E-shop dává smysl pro kontaktní čočky a roztoky.'),
       ('Jak konkurovat řetězcům?', 'Osobním přístupem, odborností a lokální dohledatelností. Web to musí ukázat.')]),
dict(slug='fitness-trener', name='Web pro fitness a osobního trenéra', short='fitness / osobní trenér', group='Krása a zdraví',
  problem='Trenér nebo fitko prodává výsledky a motivaci. Web, který neukáže proměny klientů, ceník a jak začít, neprodá ani první trénink.',
  must=['Jasná nabídka (osobní trénink, skupinové lekce, online plány)', 'Ceník a permanentky', 'Proměny a reference klientů', 'Rozvrh lekcí', 'Rezervace tréninku', 'Profil trenéra a certifikace', 'Úvodní konzultace zdarma', 'Kontakt a mapa'],
  pages=['Úvod', 'Služby', 'Ceník', 'Rozvrh', 'Proměny', 'O mně', 'Rezervace', 'Kontakt'],
  features=['Rezervace lekcí', 'Online platby a permanentky', 'Prodej online plánů'],
  seo=['„Osobní trenér + město“, „fitness + město“', 'Články o tréninku a výživě', 'Recenze s výsledky'],
  faq=[('Jde přes web prodávat tréninkové plány?', 'Ano – online platba a automatické doručení PDF nebo přístupu do členské sekce.'),
       ('Jak ukázat výsledky klientů?', 'Fotky „před a po“ se souhlasem klientů a krátké příběhy. Je to nejsilnější prodejní argument.')]),
dict(slug='joga-studio', name='Web pro jóga studio', short='jóga studio', group='Krása a zdraví',
  problem='Jóga studio potřebuje web, který je stejně klidný jako lekce – a zároveň funkční: rozvrh, rezervace, permanentky. Bez toho studenti tápou a odcházejí.',
  must=['Aktuální rozvrh lekcí', 'Online rezervace a permanentky', 'Popis stylů jógy a úrovní', 'Lektoři', 'Ceník', 'Workshopy a pobyty', 'Pro začátečníky', 'Kontakt'],
  pages=['Úvod', 'Rozvrh', 'Ceník', 'Styly jógy', 'Lektoři', 'Workshopy', 'Kontakt'],
  features=['Rezervační systém s permanentkami', 'Newsletter', 'Online lekce'],
  seo=['„Jóga + město“, „jóga pro začátečníky + město“', 'Stránky workshopů a pobytů', 'Články o józe'],
  faq=[('Jak řešit permanentky a rezervace?', 'Napojíme rezervační systém, kde si studenti koupí permanentku a sami si zapisují lekce.'),
       ('Má smysl nabízet online lekce?', 'Ano, jako doplněk – rozšíří studio o klienty, kteří nemohou dorazit osobně.')]),
# ---------------- Ubytování a gastro ----------------
dict(slug='penzion', name='Web pro penzion', short='penzion', group='Ubytování a gastro', ref='ubytovani',
  problem='Penziony platí rezervačním portálům 15–20 % z každé rezervace. Kvalitní web s přímou rezervací tyhle provize výrazně snižuje – jenže většina penzionů má web, kde chybí ceny, volné termíny a pořádné fotky.',
  must=['Velké kvalitní fotky pokojů i okolí', 'Přehled pokojů s cenami a vybavením', 'Kalendář obsazenosti nebo rezervační formulář', 'Výhoda přímé rezervace (nejlepší cena, sleva)', 'Jazykové verze (DE, PL, EN)', 'Tipy na výlety v okolí', 'Recenze hostů', 'Mapa, parkování, check-in'],
  pages=['Úvod', 'Pokoje', 'Ceník', 'Rezervace', 'Okolí a výlety', 'Galerie', 'Kontakt'],
  features=['Rezervační systém nebo channel manager', 'Online platba zálohy', 'Jazykové verze', 'Google Hotel Ads / Firemní profil'],
  seo=['„Penzion + lokalita“ (např. penzion Jeseníky)', 'Stránky s tipy na výlety přivádějí návštěvníky celý rok', 'Recenze na Googlu'],
  faq=[('Vyplatí se vlastní rezervace místo Bookingu?', 'Ano – každá přímá rezervace je bez provize. Web Booking nenahradí, ale postupně přesune část hostů na přímé rezervace.'),
       ('Potřebuji jazykové verze?', 'V turistických oblastech určitě – zejména němčinu a polštinu. Hosté z Polska a Německa tvoří velkou část návštěvníků.')]),
dict(slug='apartmany', name='Web pro apartmány', short='apartmány', group='Ubytování a gastro', ref='ubytovani',
  problem='Apartmány soupeří s desítkami nabídek na portálech. Vlastní web je místo, kde ukážete víc než konkurence – a kde host zaplatí méně, protože nepřiplácí provizi.',
  must=['Samostatná stránka pro každý apartmán', 'Fotky, půdorys a vybavení', 'Ceník podle sezóny a délky pobytu', 'Kalendář obsazenosti synchronizovaný s portály', 'Online rezervace a platba', 'Pravidla pobytu a check-in', 'Okolí a aktivity', 'Recenze'],
  pages=['Úvod', 'Apartmány', 'Ceník', 'Rezervace', 'Okolí', 'Pravidla', 'Kontakt'],
  features=['Synchronizace kalendáře (iCal) s Bookingem a Airbnb', 'Online platby', 'Jazykové verze'],
  seo=['„Apartmány + lokalita“', 'Obsah o sezónních aktivitách (lyže, cyklo)', 'Rychlé načítání fotek na mobilu'],
  faq=[('Jde synchronizovat obsazenost s Bookingem a Airbnb?', 'Ano, přes iCal nebo channel manager – volné termíny se aktualizují automaticky a nehrozí dvojí rezervace.'),
       ('Kolik stránek potřebuje web apartmánů?', 'Typicky 6–12: úvod, stránka pro každý apartmán, ceník, rezervace, okolí a kontakt.')]),
dict(slug='chata-chalupa', name='Web pro pronájem chaty a chalupy', short='chata / chalupa k pronájmu', group='Ubytování a gastro', ref='ubytovani',
  problem='Chalupy se pronajímají hlavně skupinám a rodinám, které chtějí vidět všechno: pokoje, kuchyň, okolí, kapacitu. Jedna galerie na Facebooku nestačí.',
  must=['Kapacita a rozložení pokojů', 'Fotky interiéru, exteriéru a okolí', 'Vybavení (sauna, krb, gril, Wi-Fi)', 'Ceník za noc / týden a podmínky', 'Kalendář obsazenosti', 'Pravidla (zvířata, kauce, úklid)', 'Výlety v okolí', 'Rezervační formulář'],
  pages=['Úvod', 'Chalupa', 'Ceník a obsazenost', 'Okolí', 'Pravidla', 'Rezervace'],
  features=['Kalendář obsazenosti', 'Platba zálohy', 'Jazykové verze'],
  seo=['„Chata k pronájmu + oblast“, „chalupa pro skupiny“', 'Obsah o aktivitách v okolí', 'Kvalitní fotky s popisky'],
  faq=[('Stačí jednostránkový web pro jednu chalupu?', 'Často ano – vše na jedné stránce s kotvami: fotky, vybavení, ceník, kalendář a rezervace.'),
       ('Jak řešit zálohy a kauce?', 'Online platbou zálohy a jasnými podmínkami na webu – méně dohadování, víc jistoty.')]),
dict(slug='glamping', name='Web pro glamping', short='glamping', group='Ubytování a gastro',
  problem='Glamping prodává zážitek a atmosféru. Web musí na první pohled vtáhnout – velké fotky, příběh místa – a zároveň umožnit rychlou rezervaci, protože víkendy se vyprodávají rychle.',
  must=['Atmosférické fotky a video', 'Typy ubytování (stany, maringotky, domky)', 'Co je v ceně (snídaně, sauna, vířivka)', 'Kalendář a online rezervace', 'Dárkové poukazy', 'Pravidla a příjezd', 'Okolí a zážitky', 'Recenze'],
  pages=['Úvod', 'Ubytování', 'Zážitky', 'Ceník', 'Rezervace', 'Poukazy', 'Kontakt'],
  features=['Rezervační systém s platbou', 'Prodej poukazů', 'Instagram'],
  seo=['„Glamping + region“', 'Obsah o romantických a netradičních pobytech', 'Spolupráce s cestovatelskými blogy'],
  faq=[('Jak prodávat poukazy na glamping?', 'Online prodejem s okamžitým doručením – poukazy na zážitkové pobyty jsou oblíbený dárek.'),
       ('Potřebuji video?', 'Není nutné, ale krátké video atmosféry výrazně zvyšuje počet rezervací.')]),
dict(slug='hotel', name='Web pro hotel', short='hotel', group='Ubytování a gastro',
  problem='Malé a střední hotely ztrácejí marži na portálech a jejich web často jen opakuje informace z Bookingu. Dobrý hotelový web prodává přímo – balíčky, wellness, firemní akce.',
  must=['Pokoje s fotkami a cenami', 'Booking engine s nejlepší cenou', 'Balíčky a pobyty', 'Restaurace a wellness', 'Firemní akce a svatby', 'Jazykové verze', 'Recenze', 'Poloha a doprava'],
  pages=['Úvod', 'Pokoje', 'Pobytové balíčky', 'Restaurace', 'Wellness', 'Firemní akce', 'Galerie', 'Kontakt'],
  features=['Booking engine', 'Prodej voucherů', 'Jazykové verze', 'Google Hotel Ads'],
  seo=['„Hotel + lokalita“', 'Stránky pro balíčky a sezónní pobyty', 'Lokální obsah'],
  faq=[('Napojíte náš rezervační systém?', 'Ano – běžné booking enginy a channel managery napojíme tak, aby rezervace na webu byla stejně pohodlná jako na portálech.'),
       ('Kolik stránek má hotelový web?', 'Obvykle 15–40 podle počtu jazyků, pokojů a služeb.')]),
dict(slug='restaurace', name='Web pro restauraci', short='restaurace', group='Ubytování a gastro',
  problem='Hosté chtějí na mobilu za pár sekund zjistit tři věci: menu, otevírací dobu a jestli je volný stůl. Restaurace s PDF menu, které se na mobilu nedá číst, přichází o hosty každý den.',
  must=['Menu jako text (ne PDF) – stálé i denní', 'Otevírací doba a aktuální změny', 'Rezervace stolu online', 'Fotky jídel a interiéru', 'Akce, degustace, uzavřené společnosti', 'Rozvoz / take-away', 'Recenze', 'Mapa a parkování'],
  pages=['Úvod', 'Menu', 'Denní nabídka', 'Rezervace', 'Akce a firemní večírky', 'Galerie', 'Kontakt'],
  features=['Rezervace stolů', 'Snadná úprava denního menu', 'Google Firemní profil s menu'],
  seo=['„Restaurace + město“, „polední menu + město“', 'Denní menu jako text = čerstvý obsah', 'Fotky jídel s popisky'],
  faq=[('Můžu si denní menu měnit sám?', 'Ano, jednoduše v administraci, i z mobilu. Menu se zobrazí jako text, takže ho najde i Google.'),
       ('Proč ne menu v PDF?', 'Na mobilu se špatně čte, pomalu načítá a vyhledávače ho hůř indexují. Text je rychlejší a lepší pro SEO.')]),
dict(slug='kavarna', name='Web pro kavárnu', short='kavárna', group='Ubytování a gastro',
  problem='Kavárna je o atmosféře a lidech. Na webu ji ale často neuvidíte – jen adresu a otevírací dobu. Přitom dobrý web přivede nové hosty, objednávky dortů i akce.',
  must=['Atmosférické fotky', 'Nabídka kávy, dezertů a snídaní', 'Otevírací doba', 'Objednávky dortů a cateringu', 'Akce a komunitní večery', 'Pražírna / původ kávy', 'Instagram', 'Kontakt a mapa'],
  pages=['Úvod', 'Nabídka', 'Dorty na objednávku', 'Akce', 'O nás', 'Kontakt'],
  features=['Objednávkový formulář na dorty', 'Instagram feed', 'Google profil'],
  seo=['„Kavárna + město“, „dorty na objednávku + město“', 'Akce a novinky', 'Fotky s popisky'],
  faq=[('Má kavárna mít e-shop?', 'Pokud prodáváte vlastní kávu nebo zrnkovou kávu, ano – i malý e-shop. Jinak stačí objednávky dortů a poukazy.'),
       ('Jak propojit web s Instagramem?', 'Instagram feed se zobrazí na webu automaticky a web dodá to, co Instagram neumí – vyhledatelnost na Googlu.')]),
dict(slug='cukrarna', name='Web pro cukrárnu', short='cukrárna', group='Ubytování a gastro',
  problem='Cukrárny vydělávají hlavně na dortech na objednávku – svatby, narozeniny, firemní akce. Bez přehledného katalogu a objednávkového formuláře vyřizujete vše po telefonu a o část zakázek přicházíte.',
  must=['Katalog dortů s fotkami a orientačními cenami', 'Objednávkový formulář (příchuť, velikost, termín)', 'Svatební dorty a candy bary', 'Denní nabídka zákusků', 'Alergeny', 'Termíny pro objednávky předem', 'Recenze', 'Kontakt a otevírací doba'],
  pages=['Úvod', 'Dorty na objednávku', 'Svatební dorty', 'Zákusky', 'Objednávka', 'Kontakt'],
  features=['Formulář s nahráním inspirace', 'Online záloha', 'Instagram'],
  seo=['„Dorty na objednávku + město“, „svatební dort + region“', 'Galerie realizací s popisky', 'Recenze'],
  faq=[('Jak řešit objednávky dortů online?', 'Formulářem, kde zákazník vybere velikost, příchuť, termín a nahraje inspiraci. Vy pošlete potvrzení s cenou.'),
       ('Mám uvádět ceny dortů?', 'Orientační ceny ano – ušetří to dotazy a zákazník hned ví, do čeho jde.')]),
dict(slug='minipivovar', name='Web pro minipivovar', short='minipivovar', group='Ubytování a gastro',
  problem='Minipivovar má silný příběh, ale web často ukáže jen otevírací dobu. Přitom může prodávat pivo domů, exkurze a akce – a přivádět turisty.',
  must=['Aktuální piva na čepu', 'Příběh pivovaru a sládka', 'Exkurze a degustace s rezervací', 'E-shop nebo objednávky lahví a sudů', 'Restaurace / pivnice', 'Akce a festivaly', 'Velkoodběr pro hospody', 'Kontakt'],
  pages=['Úvod', 'Naše piva', 'Na čepu', 'Exkurze', 'E-shop', 'Akce', 'Kontakt'],
  features=['E-shop s ověřením věku', 'Rezervace exkurzí', 'Newsletter'],
  seo=['„Minipivovar + region“, „exkurze pivovar + region“', 'Stránky jednotlivých piv', 'Turistický obsah'],
  faq=[('Můžeme prodávat pivo přes web?', 'Ano, s ověřením věku a odběrem na místě nebo rozvozem dle podmínek. Velmi oblíbené jsou dárkové sady.'),
       ('Jak přilákat turisty?', 'Exkurzemi s online rezervací a obsahem o okolí – web se pak ukazuje i lidem, kteří plánují výlet.')]),
dict(slug='catering', name='Web pro catering', short='catering', group='Ubytování a gastro',
  problem='Catering se prodává přes důvěru a rychlou nabídku. Firma, která potřebuje raut na příští týden, nechce čekat tři dny na odpověď – chce vidět menu, ceny na osobu a poptat jedním formulářem.',
  must=['Typy akcí (firemní, svatby, oslavy)', 'Ukázková menu a ceny na osobu', 'Chytrý poptávkový formulář (počet osob, termín, typ)', 'Fotky realizací', 'Reference firem', 'Doprava a obsluha', 'Alergeny a speciální diety', 'Kontakt'],
  pages=['Úvod', 'Firemní catering', 'Svatby', 'Oslavy', 'Menu a ceny', 'Reference', 'Poptávka'],
  features=['Poptávkový formulář s kalkulací', 'Galerie realizací', 'Reference'],
  seo=['„Catering + město/region“, „svatební catering“', 'Stránky typů akcí', 'Reference firem'],
  faq=[('Dá se na webu udělat orientační kalkulačka?', 'Ano – podle počtu osob a typu menu web spočítá orientační cenu a pošle poptávku.'),
       ('Co nejvíc prodává catering?', 'Fotky z reálných akcí a reference firem. Tím získáte důvěru dřív, než zavoláte.')]),
dict(slug='food-truck', name='Web pro food truck', short='food truck', group='Ubytování a gastro',
  problem='Food truck je každý den jinde. Fanoušci chtějí vědět, kde vás najdou, a firmy chtějí rychle objednat na akci. Bez webu se ztrácíte mezi příspěvky na sociálních sítích.',
  must=['Kalendář míst, kde stojíte', 'Menu a ceny', 'Objednání na firemní akce a svatby', 'Fotky jídla a vozu', 'Napojení na Instagram a Facebook', 'Reference akcí', 'Kontakt', 'Novinky'],
  pages=['Úvod', 'Kde nás najdete', 'Menu', 'Na akce', 'Galerie', 'Kontakt'],
  features=['Kalendář akcí', 'Poptávkový formulář', 'Sociální sítě'],
  seo=['„Food truck + region“, „food truck na svatbu“', 'Stránka pro akce', 'Pravidelné novinky'],
  faq=[('Jak udržet kalendář aktuální?', 'Jednoduchou úpravou v administraci nebo napojením na Google Kalendář.'),
       ('Má food truck smysl mít web?', 'Ano – hlavně kvůli objednávkám na akce. Firmy hledají na Googlu, ne na Instagramu.')]),
]
