"""Oborové landing pages – část B: svatby a události, řemesla a stavby."""

B = [
# ---------------- Svatby a události ----------------
dict(slug='svatebni-web', name='Svatební web', short='svatební web pro snoubence', group='Svatby a události',
  problem='Hosté se ptají pořád na totéž: kdy, kde, jak se tam dostat, kde spát, co si obléct, co darovat. Svatební web odpoví za vás – a zároveň sbírá potvrzení účasti, jídlo i písničky, takže nemusíte vést tabulky a obvolávat půl rodiny.',
  must=['Datum, místo a harmonogram dne', 'Potvrzení účasti (RSVP) online s výběrem menu a alergií', 'Mapa, doprava a parkování', 'Ubytování pro hosty', 'Dress code', 'Svatební dary / seznam přání', 'Náš příběh a fotky', 'Sdílení fotek po svatbě'],
  pages=['Úvod s odpočtem', 'Náš příběh', 'Program dne', 'Místo a doprava', 'Ubytování', 'Potvrzení účasti', 'Dary', 'Fotky po svatbě'],
  features=['RSVP formulář s exportem do tabulky', 'Heslem chráněný web', 'Odpočet do svatby', 'Galerie pro sdílení fotek hostů'],
  seo=['Svatební web obvykle indexovat nechcete – nastavíme ho jako soukromý', 'Vlastní doména, např. janaapetr.cz', 'Snadné sdílení odkazu a QR kódu na oznámení'],
  faq=[('Proč ne svatební web zdarma?', 'Bezplatné nástroje jsou šablonovité, plné reklam a omezené. Web na míru vypadá jako vaše svatba, má vlastní doménu a RSVP přesně podle vašich potřeb.'),
       ('Jak dlouho svatební web vydrží?', 'Jak dlouho chcete – po svatbě ho můžeme proměnit v galerii fotek pro hosty a rodinu.'),
       ('Kolik stojí svatební web na míru?', 'Jednodušší svatební web s RSVP začíná na nižší cenové hladině než firemní web. Přesnou nabídku dostanete po krátké konzultaci zdarma.')]),
dict(slug='svatebni-fotograf', name='Web pro svatebního fotografa', short='svatební fotograf', group='Svatby a události',
  problem='Snoubenci si fotografa vybírají podle stylu a pocitu z fotek. Portfolio musí být rychlé, velké a krásné – a pak hned odpovědět na otázku „máte volno v náš termín a kolik to stojí?“.',
  must=['Portfolio celých svateb, ne jen best-of', 'Balíčky a ceny', 'Kontrola volného termínu / poptávka', 'Recenze párů', 'O mně – styl a přístup', 'Průběh spolupráce', 'FAQ (kolik fotek, kdy budou, cestovné)', 'Rychlé načítání velkých fotek'],
  pages=['Úvod', 'Portfolio', 'Svatby (příběhy)', 'Balíčky a ceny', 'O mně', 'Recenze', 'Poptávka'],
  features=['Optimalizace velkých fotek (WebP, lazy load)', 'Poptávkový formulář s termínem', 'Klientské galerie'],
  seo=['„Svatební fotograf + region“, „svatební fotograf Jeseníky“', 'Blog s příběhy svateb a míst', 'Popisky a alt texty fotek'],
  faq=[('Jak ukázat stovky fotek a nezpomalit web?', 'Moderní formáty (WebP), postupné načítání a správné velikosti – web zůstane rychlý i s velkým portfoliem.'),
       ('Má smysl psát blog o svatbách?', 'Ano – každá svatba je příběh s místem a jmény, které lidé hledají. Je to nejlepší SEO pro svatební fotografy.')]),
dict(slug='kameraman', name='Web pro kameramana a videotvůrce', short='kameraman', group='Svatby a události',
  problem='Video se prodává videem. Web kameramana ale často načítá deset minut nebo ukazuje jen odkazy na YouTube. Klient chce během pár vteřin vidět ukázku, styl a cenu.',
  must=['Showreel na úvodní stránce', 'Portfolio rozdělené podle typu (svatby, firmy, reklama)', 'Balíčky a ceny', 'Průběh spolupráce', 'Technika a tým', 'Recenze', 'Poptávkový formulář', 'Rychlé načítání videí'],
  pages=['Úvod', 'Portfolio', 'Svatby', 'Firemní videa', 'Ceník', 'O nás', 'Poptávka'],
  features=['Optimalizované vkládání videí (Vimeo/YouTube bez zpomalení)', 'Poptávkový formulář', 'Recenze'],
  seo=['„Svatební kameraman + region“, „firemní video + město“', 'Textové popisy ke každému videu', 'Případové studie'],
  faq=[('Jak vložit videa, aby web nebyl pomalý?', 'Videa se načtou až po kliknutí (lite embed) – web zůstane rychlý a video se přehraje v plné kvalitě.'),
       ('Mám mít na webu ceník?', 'Alespoň orientační balíčky. Klienti s představou o rozpočtu se ozvou mnohem častěji.')]),
dict(slug='svatebni-koordinatorka', name='Web pro svatební koordinátorku', short='svatební koordinátorka', group='Svatby a události',
  problem='Svatební koordinátorka prodává klid a jistotu. Web musí působit elegantně, ukázat realizované svatby a srozumitelně vysvětlit, co přesně dostane pár za svoje peníze.',
  must=['Služby (kompletní organizace, koordinace dne, dekorace)', 'Balíčky a ceny', 'Realizované svatby s fotkami', 'Recenze párů', 'Průběh spolupráce', 'Spolupracující dodavatelé', 'Svatební místa v regionu', 'Poptávka s termínem'],
  pages=['Úvod', 'Služby', 'Balíčky', 'Realizace', 'Jak spolupracujeme', 'Recenze', 'Kontakt'],
  features=['Poptávkový formulář', 'Galerie realizací', 'Blog'],
  seo=['„Svatební koordinátorka + region“', 'Obsah o svatebních místech v okolí', 'Případové studie svateb'],
  faq=[('Co nejvíc prodává služby koordinátorky?', 'Reálné svatby s příběhem a recenze párů. Pár musí cítit, že se o nic nemusí starat.'),
       ('Může web propagovat i svatební místa, se kterými spolupracuji?', 'Ano – stránky o svatebních místech v regionu přitáhnou páry, které teprve začínají plánovat.')]),
dict(slug='svatebni-misto', name='Web pro svatební místo a statek', short='svatební místo / statek', group='Svatby a události',
  problem='Páry vybírají místo pro svatbu rok i dva dopředu a porovnávají desítky možností. Pokud web neukáže kapacitu, ceny, volné termíny a skutečné fotky ze svateb, dostanete se na konec seznamu.',
  must=['Fotky prostor a skutečných svateb', 'Kapacita (obřad, hostina, ubytování)', 'Ceník a balíčky', 'Volné termíny', 'Catering a spolupracující dodavatelé', 'Ubytování pro hosty', 'Virtuální prohlídka nebo video', 'Poptávka a prohlídka místa'],
  pages=['Úvod', 'Prostory', 'Svatby u nás', 'Ceník', 'Ubytování', 'Dodavatelé', 'Termíny', 'Poptávka'],
  features=['Kalendář volných termínů', 'Objednání prohlídky', 'Galerie'],
  seo=['„Svatební místo + region“, „svatba na statku“', 'Příběhy svateb', 'Firemní akce jako druhý pilíř'],
  faq=[('Mám zveřejnit volné termíny?', 'Ano – páry tím hned filtrují. Kalendář si můžete jednoduše aktualizovat sami.'),
       ('Hodí se web i pro firemní akce?', 'Určitě – samostatná sekce pro firemní akce a večírky vyplní termíny mimo svatební sezónu.')]),
dict(slug='dj-kapela', name='Web pro DJ a kapelu', short='DJ / kapela', group='Svatby a události',
  problem='Na svatbu nebo firemní večírek si lidé vybírají hudbu podle ukázek a referencí. Odkaz na Facebook nestačí – potřebují slyšet, vidět a rychle poptat termín.',
  must=['Ukázky – audio a video', 'Repertoár a styly', 'Balíčky a ceny', 'Technika (zvuk, světla)', 'Reference a recenze', 'Volné termíny', 'Poptávkový formulář', 'Kontakt'],
  pages=['Úvod', 'Ukázky', 'Repertoár', 'Ceník', 'Reference', 'Poptávka'],
  features=['Audio přehrávač', 'Poptávkový formulář s termínem', 'Recenze'],
  seo=['„DJ na svatbu + region“, „kapela na firemní večírek“', 'Reference z konkrétních akcí', 'Video ukázky s popisy'],
  faq=[('Stačí jednostránkový web?', 'Ano – ukázky, repertoár, ceny, reference a poptávka se vejdou na jednu přehlednou stránku.'),
       ('Jak ukázat, že umím svatby?', 'Recenzemi párů a krátkým videem ze svatby. To prodává nejvíc.')]),
dict(slug='kvetinarstvi', name='Web pro květinářství', short='květinářství', group='Svatby a události',
  problem='Květiny se dnes objednávají online – k narozeninám, na svatbu, na poslední chvíli. Květinářství bez možnosti objednávky přichází o zakázky, které jdou k velkým e-shopům.',
  must=['Online objednávka kytic s doručením', 'Svatební floristika', 'Smuteční vazby', 'Firemní výzdoba a pravidelné zakázky', 'Rozvoz po městě a okolí', 'Fotky realizací', 'Otevírací doba', 'Kontakt'],
  pages=['Úvod', 'Kytice (e-shop)', 'Svatby', 'Smuteční vazby', 'Pro firmy', 'Rozvoz', 'Kontakt'],
  features=['Jednoduchý e-shop s doručením', 'Výběr data doručení', 'Online platby'],
  seo=['„Květinářství + město“, „rozvoz květin + město“', 'Sezónní stránky (Valentýn, Den matek)', 'Svatební floristika'],
  faq=[('Vyplatí se malému květinářství e-shop?', 'Ano, i s pár desítkami kytic. Lidé chtějí objednat a zaplatit online – hlavně když posílají květiny někomu jinému.'),
       ('Jak řešit doručení?', 'Výběrem data a času doručení, zónami rozvozu a příplatky – vše přehledně v objednávce.')]),
# ---------------- Řemesla a stavby ----------------
dict(slug='stavebni-firma', name='Web pro stavební firmu', short='stavební firma', group='Řemesla a stavby',
  problem='Stavební firmy často spoléhají na doporučení – a web mají zastaralý nebo žádný. Investor si vás ale před poptávkou vždy vygoogluje. Pokud neuvidí realizace a jasné služby, zavolá jinam.',
  must=['Služby (novostavby, rekonstrukce, zateplení…)', 'Realizace s fotkami před/po a popisem', 'Region působnosti', 'Postup spolupráce', 'Certifikace a pojištění', 'Reference investorů', 'Poptávkový formulář s nahráním podkladů', 'Kariéra – nábor řemeslníků'],
  pages=['Úvod', 'Služby', 'Realizace', 'Jak pracujeme', 'O firmě', 'Kariéra', 'Kontakt / poptávka'],
  features=['Formulář s přílohami (projekt, fotky)', 'Galerie realizací', 'Kariérní stránka'],
  seo=['„Stavební firma + město“, „rekonstrukce domu + region“', 'Stránka pro každou službu', 'Popsané realizace s lokalitou'],
  faq=[('Proč potřebuje stavební firma web, když má práce dost?', 'Kvůli lepším zakázkám a náboru. Kvalitní web přivádí investory s vyšším rozpočtem a pomáhá najít řemeslníky.'),
       ('Jak ukázat realizace?', 'Stránkou pro každou zakázku – fotky před, během a po, rozsah prací a lokalita. To je zároveň skvělé SEO.')]),
dict(slug='instalater', name='Web pro instalatéra a topenáře', short='instalatér / topenář', group='Řemesla a stavby',
  problem='Když teče voda nebo nejde topení, lidé hledají instalatéra na mobilu a volají prvnímu, kdo vypadá důvěryhodně. Bez webu a Google profilu vás nenajdou.',
  must=['Telefon na jeden klik na mobilu', 'Služby (havárie, rozvody, kotle, tepelná čerpadla)', 'Region působnosti', 'Pohotovost a dostupnost', 'Orientační ceny / ceník výjezdu', 'Fotky prací', 'Recenze', 'Poptávkový formulář'],
  pages=['Úvod', 'Služby', 'Havárie a pohotovost', 'Ceník', 'Realizace', 'Kontakt'],
  features=['Tlačítko „Zavolat“ na mobilu', 'Google Firemní profil', 'Recenze'],
  seo=['„Instalatér + město“, „oprava kotle + město“', 'Stránky pro jednotlivé služby', 'Recenze s popisem zakázky'],
  faq=[('Stačí řemeslníkovi jednoduchý web?', 'Ano – i 4–6 stránek s jasnými službami, regionem a telefonem přivede zakázky. Hlavní je dohledatelnost a důvěra.'),
       ('Jak získat recenze?', 'Po každé zakázce pošlete odkaz na hodnocení – web je pak zobrazí a Google vás posune výš.')]),
dict(slug='elektrikar', name='Web pro elektrikáře', short='elektrikář', group='Řemesla a stavby',
  problem='Elektrikáři mají práce dost, ale často ne té správné. Web pomůže přivést zakázky, které chcete – revize, fotovoltaiky, chytré domácnosti – místo drobností.',
  must=['Služby (rozvody, revize, fotovoltaika, wallboxy, chytrá domácnost)', 'Certifikace a oprávnění', 'Region působnosti', 'Realizace', 'Orientační ceny', 'Recenze', 'Poptávkový formulář', 'Telefon na jeden klik'],
  pages=['Úvod', 'Služby', 'Revize', 'Fotovoltaika', 'Realizace', 'Kontakt'],
  features=['Poptávka s fotkami', 'Google profil', 'Recenze'],
  seo=['„Elektrikář + město“, „revize elektro + město“, „wallbox instalace“', 'Stránky pro ziskové služby', 'Realizace s lokalitou'],
  faq=[('Jak přes web získat víc zakázek na fotovoltaiku?', 'Samostatnou stránkou s vysvětlením, realizacemi a kalkulací – lidé hledají konkrétní řešení, ne obecného elektrikáře.'),
       ('Musím mít na webu oprávnění?', 'Je to silný signál důvěry. Uvést číslo oprávnění a certifikace se vyplatí.')]),
dict(slug='truhlar', name='Web pro truhláře a výrobu nábytku na míru', short='truhlářství', group='Řemesla a stavby',
  problem='Nábytek na míru je investice a zákazník chce vidět kvalitu. Fotky ze stolu pod zářivkou ani jedna stránka s telefonem ho nepřesvědčí.',
  must=['Kvalitní fotky realizací (kuchyně, vestavné skříně, schody)', 'Postup – od zaměření po montáž', 'Materiály a dřeviny', 'Orientační ceny nebo ceny za běžný metr', 'Poptávka s nahráním rozměrů a fotek', 'Region působnosti', 'Recenze', 'Showroom / dílna'],
  pages=['Úvod', 'Kuchyně', 'Vestavné skříně', 'Další nábytek', 'Realizace', 'Jak to probíhá', 'Poptávka'],
  features=['Formulář s přílohami', 'Galerie podle kategorií', 'Recenze'],
  seo=['„Kuchyně na míru + region“, „truhlářství + město“', 'Realizace s popisem a lokalitou', 'Stránky podle typu nábytku'],
  faq=[('Jak ukázat kvalitu práce?', 'Profesionálními fotkami realizací a detaily spojů a materiálů. Rádi doporučíme fotografa.'),
       ('Dá se na webu uvést cena?', 'Orientačně ano – např. „kuchyně od 80 000 Kč“. Filtruje to poptávky a šetří čas.')]),
dict(slug='pokryvac', name='Web pro pokrývače a klempíře', short='pokrývač / klempíř', group='Řemesla a stavby',
  problem='Střecha je drahá zakázka a zákazník chce jistotu. Pokud z webu nepozná, že děláte přesně jeho typ střechy, a nevidí reference, nezavolá.',
  must=['Služby (nové střechy, rekonstrukce, opravy, klempířina, okapy)', 'Typy krytin', 'Realizace s fotkami', 'Záruky', 'Region působnosti', 'Postup a termíny', 'Poptávka s fotkou střechy', 'Recenze'],
  pages=['Úvod', 'Služby', 'Krytiny', 'Realizace', 'Záruky', 'Kontakt'],
  features=['Poptávka s fotkami', 'Galerie', 'Google profil'],
  seo=['„Pokrývač + město“, „oprava střechy + region“', 'Stránky typů krytin', 'Realizace s lokalitou'],
  faq=[('Jaké stránky by neměl web pokrývače vynechat?', 'Realizace a záruky. Přesně tyhle dvě věci zákazníky přesvědčí nejvíc.'),
       ('Jak řešit poptávky na opravy?', 'Formulářem, kam zákazník nahraje fotky střechy – můžete dát orientační cenu bez výjezdu.')]),
dict(slug='malir-pokoju', name='Web pro malíře pokojů a natěrače', short='malíř pokojů', group='Řemesla a stavby',
  problem='Malíři soutěží hlavně cenou a termínem. Web s jasnými cenami za m², rychlou poptávkou a fotkami čistě odvedené práce vás odliší od konkurence z inzerátů.',
  must=['Ceník za m² a doplňkové práce', 'Rychlá poptávka s rozměry', 'Termíny a dostupnost', 'Fotky realizací', 'Zakrývání a úklid – čistota práce', 'Region', 'Recenze', 'Telefon na jeden klik'],
  pages=['Úvod', 'Služby', 'Ceník', 'Realizace', 'Kontakt'],
  features=['Kalkulačka ceny podle m²', 'Poptávkový formulář', 'Google recenze'],
  seo=['„Malíř pokojů + město“, „malování bytu cena“', 'Jasný ceník', 'Recenze'],
  faq=[('Má smysl kalkulačka ceny?', 'Ano – zákazník si spočítá orientační cenu a poptá s konkrétní představou. Méně zbytečných výjezdů.'),
       ('Stačí jedna stránka?', 'Pro malíře často ano – služby, ceník, fotky a poptávka na jedné stránce.')]),
dict(slug='zahradnik', name='Web pro zahradníka a údržbu zahrad', short='zahradník / údržba zahrad', group='Řemesla a stavby',
  problem='Zakládání a údržba zahrad je sezónní byznys. Kdo má web připravený na jaro, sbírá poptávky už v únoru – ostatní pak honí zakázky na poslední chvíli.',
  must=['Služby (realizace zahrad, údržba, sekání, kácení, závlahy)', 'Pravidelná údržba – paušály', 'Realizace před/po', 'Region', 'Sezónní nabídky', 'Poptávka s fotkami zahrady', 'Recenze', 'Kontakt'],
  pages=['Úvod', 'Realizace zahrad', 'Údržba', 'Kácení', 'Realizace', 'Kontakt'],
  features=['Poptávka s přílohami', 'Galerie', 'Sezónní banner'],
  seo=['„Údržba zahrad + město“, „realizace zahrad + region“', 'Sezónní obsah', 'Realizace s lokalitou'],
  faq=[('Kdy je nejlepší čas spustit web zahradníka?', 'V zimě – lidé začínají plánovat zahradu v únoru a březnu. Web musí být vidět dřív, než začne sezóna.'),
       ('Jak prodávat pravidelnou údržbu?', 'Paušálními balíčky na webu – zákazník ví, co dostane, a vy máte stabilní příjem.')]),
dict(slug='autoservis', name='Web pro autoservis', short='autoservis', group='Řemesla a stavby',
  problem='Řidiči hledají servis podle značky, služby a dostupnosti termínu. Autoservis bez online objednání a jasných služeb ztrácí zákazníky ve prospěch řetězců.',
  must=['Služby (servis, STK příprava, pneu, klimatizace, diagnostika)', 'Značky, na které se specializujete', 'Online objednání termínu', 'Orientační ceník', 'Náhradní vůz / odvoz', 'Recenze', 'Otevírací doba a mapa', 'Telefon na jeden klik'],
  pages=['Úvod', 'Služby', 'Ceník', 'Objednání', 'O servisu', 'Kontakt'],
  features=['Online objednávka termínu', 'Google profil', 'Recenze'],
  seo=['„Autoservis + město“, „servis Škoda + město“, „plnění klimatizace + město“', 'Stránky služeb', 'Recenze'],
  faq=[('Má smysl online objednávání v autoservisu?', 'Ano – řidiči si chtějí vybrat termín večer, ne volat přes den. Méně telefonátů, víc zakázek.'),
       ('Mám uvádět ceny?', 'Orientačně u běžných úkonů (výměna oleje, klimatizace, přezutí). Zvyšuje to důvěru.')]),
dict(slug='pneuservis', name='Web pro pneuservis', short='pneuservis', group='Řemesla a stavby',
  problem='Dvakrát ročně se všichni chtějí přezout ve stejný týden. Pneuservis bez online rezervace stráví sezónu u telefonu – a stejně část zákazníků odmítne.',
  must=['Online rezervace přezutí', 'Ceník přezutí podle velikosti kol', 'Uskladnění pneu', 'Prodej pneumatik', 'Otevírací doba v sezóně', 'Mapa', 'Recenze', 'Kontakt'],
  pages=['Úvod', 'Rezervace', 'Ceník', 'Uskladnění', 'Pneumatiky', 'Kontakt'],
  features=['Rezervační systém s kapacitou', 'SMS připomínky', 'Google profil'],
  seo=['„Pneuservis + město“, „přezutí pneu + město“', 'Sezónní obsah', 'Recenze'],
  faq=[('Zvládne rezervace nápor v sezóně?', 'Ano – nastavíme kapacity podle počtu zvedáků a délky přezutí, systém nepustí víc zákazníků, než zvládnete.'),
       ('Jde přes web prodávat pneumatiky?', 'Ano, i s napojením na katalog dodavatele – ale často stačí poptávka a nabídka.')]),
dict(slug='uklidova-firma', name='Web pro úklidovou firmu', short='úklidová firma', group='Řemesla a stavby',
  problem='Úklid je služba postavená na důvěře – pouštíte někoho domů nebo do kanceláře. Web musí ukázat lidi, pojištění, recenze a nabídnout rychlou kalkulaci.',
  must=['Služby (domácnosti, kanceláře, po rekonstrukci, mytí oken)', 'Kalkulace ceny podle m² / hodin', 'Pravidelný úklid – paušály', 'Pojištění a prověření pracovníků', 'Recenze', 'Region', 'Objednávka online', 'Kontakt'],
  pages=['Úvod', 'Úklid domácností', 'Úklid firem', 'Ceník', 'Objednávka', 'Kontakt'],
  features=['Kalkulačka ceny', 'Online objednávka', 'Recenze'],
  seo=['„Úklidová firma + město“, „úklid po rekonstrukci + město“', 'Stránky typů úklidu', 'Recenze'],
  faq=[('Jak zvýšit důvěru zákazníků?', 'Fotky týmu, pojištění odpovědnosti, recenze a jasné podmínky. Zákazník musí vědět, koho pouští dovnitř.'),
       ('Má smysl online kalkulačka?', 'Ano – zákazník rovnou vidí cenu a objedná. Ušetříte desítky e-mailů.')]),
dict(slug='stehovani', name='Web pro stěhovací firmu', short='stěhování', group='Řemesla a stavby',
  problem='Stěhování se poptává v časovém tlaku a lidé obesílají víc firem najednou. Vyhrává ta, u které rychle pochopí cenu a snadno poptají.',
  must=['Služby (byty, domy, firmy, piana, vyklízení)', 'Ceník – hodinová sazba, km, balení', 'Kalkulace nebo rychlá poptávka', 'Pojištění nákladu', 'Vozový park', 'Recenze', 'Region a dálková stěhování', 'Kontakt'],
  pages=['Úvod', 'Služby', 'Ceník', 'Poptávka', 'Reference', 'Kontakt'],
  features=['Poptávkový formulář s adresami', 'Kalkulačka', 'Recenze'],
  seo=['„Stěhování + město“, „stěhování bytu cena“', 'Ceník', 'Recenze'],
  faq=[('Jak získat víc poptávek na stěhování?', 'Jednoduchým formulářem (odkud, kam, kdy, kolik věcí) a jasným ceníkem. Rychlost odpovědi rozhoduje.'),
       ('Má stěhovací firma uvádět ceny?', 'Ano – hodinové sazby a příplatky. Zákazníci firmy porovnávají a bez ceny vás přeskočí.')]),
dict(slug='kominik', name='Web pro kominíka', short='kominík', group='Řemesla a stavby',
  problem='Kontrola spalinové cesty je povinná a lidé hledají kominíka většinou jednou za rok – přes Google. Kdo není vidět, toho nenajdou.',
  must=['Služby (kontroly, čištění, revize, frézování, vložkování)', 'Povinné termíny kontrol podle paliva', 'Objednání termínu', 'Ceník', 'Region', 'Oprávnění', 'Recenze', 'Kontakt'],
  pages=['Úvod', 'Služby', 'Povinné kontroly', 'Ceník', 'Objednání', 'Kontakt'],
  features=['Objednávkový formulář', 'Připomínka kontroly e-mailem', 'Google profil'],
  seo=['„Kominík + město“, „revize komína + město“', 'Informace o povinných kontrolách', 'Recenze'],
  faq=[('Jak přes web získat stálé zákazníky?', 'Připomínkou kontroly – zákazník zanechá e-mail a za rok mu automaticky přijde upozornění.'),
       ('Stačí kominíkovi jednoduchý web?', 'Ano – 3–5 stránek s jasnými službami, cenami a objednáním plně stačí.')]),
]
