# Stránky služeb – obsah. Každá stránka cílí na jednu hlavní frázi (kw) a pár příbuzných (extra).
S = [
dict(
    slug='tvorba-webovych-stranek', nav='Tvorba webových stránek',
    h1='Tvorba webových stránek', kw='tvorba webových stránek',
    extra='tvorba webu,profesionální tvorba webových stránek',
    title='Tvorba webových stránek od 9 900 Kč | wwwwww.cz',
    desc='Profesionální tvorba webových stránek pro firmy a živnostníky z celé ČR. Návrh, texty, SEO i správa pod jednou střechou. Weby od 9 900 Kč.',
    eyebrow='Hlavní služba',
    lead='Tvorba webových stránek, které nejsou jen vizitkou, ale přivádějí poptávky. Navrhneme, napíšeme a spustíme web pro vaši firmu – osobně, srozumitelně a za férovou cenu.',
    intro_h2='Tvorba webu, která začíná u vašeho byznysu',
    intro=[
        'Dobrý web nezačíná výběrem barev, ale otázkou: co má návštěvník udělat? Zavolat, poslat poptávku, rezervovat termín, nebo nakoupit? Tvorba webových stránek u nás proto začíná krátkým rozhovorem o vašich zákaznících, službách a konkurenci. Teprve potom navrhujeme strukturu, texty a design.',
        'Za wwwwww.cz stojí webové studio z Jeseníku a tým marketingové agentury Yesmark. Weby tvoříme pro řemeslníky, služby, ubytování, výrobní firmy i obce a spolky z celé České republiky. Spolupráce běží osobně nebo online – jak vám to vyhovuje.',
        'Profesionální tvorba webových stránek pro nás znamená kompletní servis: návrh, texty, fotky, technické nastavení, základní SEO, napojení na Google Analytics a předání webu tak, abyste si ho uměli sami upravovat.'],
    card_h3='Co dostanete',
    card=['Návrh struktury a designu na míru', 'Web pro mobil, tablet i počítač', 'Pomoc s texty a fotkami', 'Základní SEO a Google Firemní profil',
          'Formuláře, mapy a napojení na e-mail', 'Cookies lištu a GDPR', 'Zaškolení do administrace', 'Podporu i po spuštění'],
    grid_head=('Postup', 'Jak probíhá tvorba webových stránek', 'Osm kroků od prvního hovoru po web, který pracuje za vás. Vždy víte, v jaké fázi projekt je.'),
    grid=[('Úvodní hovor', 'Probereme cíle, zákazníky a rozpočet – telefonicky, online, nebo u kávy v Jeseníku.'),
          ('Nabídka zdarma', 'Dostanete jasnou cenu, rozsah a termín. Bez skrytých položek.'),
          ('Struktura webu', 'Navrhneme, jaké stránky web potřebuje a jak po nich návštěvník dojde k poptávce.'),
          ('Obsah', 'Pomůžeme s texty, které prodávají a zároveň dobře fungují ve vyhledávačích.'),
          ('Design', 'Grafický návrh v duchu vaší značky. Připomínkujete, dokud nejste spokojení.'),
          ('Realizace', 'Web postavíme na WordPressu s Elementorem, u individuálních projektů na October CMS.'),
          ('Spuštění', 'Doména, hosting, SSL, Analytics, Search Console a kontrola všech formulářů.'),
          ('Péče po spuštění', 'Aktualizace, zálohy, úpravy a další rozvoj webu podle výsledků.')],
    deep_h2='Proč tvorba webu na míru místo šablony',
    deep='<p>Web z online stavebnice vypadá podobně jako tisíce dalších a často naráží na limity – v SEO, ve vlastnictví dat i v možnostech dalšího rozvoje. Tvorba webu na míru znamená, že strukturu, texty i design přizpůsobíme vašemu oboru a zákazníkům.</p>'
         '<h3>Web, který si upravíte sami</h3><p>Stavíme převážně na WordPressu a Elementoru. Texty, fotky, ceník nebo novou stránku změníte sami bez programátora. Ukážeme vám, jak na to, a když budete chtít, úpravy převezmeme.</p>'
         '<h3>SEO od prvního dne</h3><p>Každá stránka má promyšlené nadpisy, popisky, interní odkazy a strukturovaná data. Web tak má od začátku šanci ukázat se lidem, kteří hledají vaše služby na Googlu.</p>'
         '<h3>Pro klienty z celé České republiky</h3><p>Sídlíme v Jeseníku, ale tvorba webových stránek u nás není vázaná na region. Pracujeme pro klienty z Olomouckého, Moravskoslezského i Pardubického kraje a z celého Česka.</p>',
    faq=[('Kolik stojí tvorba webových stránek?', 'Tvorba webových stránek začíná na 9 900 Kč. Cena záleží na počtu stránek, funkcích a grafickém zpracování. Podrobnosti najdete na stránce <a href="/kolik-stoji-web/">Kolik stojí web</a>.'),
         ('Jak dlouho trvá tvorba webu?', 'Jednodušší prezentační web bývá hotový za 2–4 týdny, rozsáhlejší web nebo e-shop za 4–8 týdnů. Přesný harmonogram dostanete v nabídce.'),
         ('Co od vás budete potřebovat?', 'Hlavně informace o vašich službách, logo a ideálně vlastní fotky. S texty rádi pomůžeme.'),
         ('Na jakém systému web postavíte?', 'Nejčastěji na WordPressu s Elementorem, u individuálních projektů na October CMS. Web je vždy ve vašem vlastnictví.'),
         ('Pomůžete s doménou a hostingem?', 'Ano. Doménu i hosting zařídíme, nebo web napojíme na ty, které už máte.')],
),
dict(
    slug='kolik-stoji-web', nav='Kolik stojí web',
    h1='Kolik stojí web', kw='kolik stojí web',
    extra='tvorba webových stránek cena,tvorba webových stránek ceník,tvorba webu cena,kolik stojí tvorba webových stránek,tvorba webových stránek levně',
    title='Kolik stojí web? Ceník tvorby webu 2026 | wwwwww.cz',
    desc='Kolik stojí web pro firmu nebo živnostníka? Co ovlivňuje cenu tvorby webových stránek, kolik stojí provoz a kde se dá ušetřit. Weby od 9 900 Kč.',
    eyebrow='Cena a ceník',
    lead='Kolik stojí web? Poctivá odpověď zní: záleží na tom, co má umět. Na této stránce najdete, co cenu tvorby webových stránek ovlivňuje, kolik stojí provoz a kde se dá rozumně ušetřit.',
    intro_h2='Kolik stojí web u nás',
    intro=[
        'Jednodušší prezentační web u nás začíná na <strong>9 900 Kč</strong>. Za tu cenu dostanete moderní web pro mobil i počítač, kontaktní formulář, základní SEO a zaškolení do administrace.',
        'Kolik stojí web s více stránkami, rezervacemi, jazykovými verzemi nebo e-shopem, spočítáme individuálně. Nabídku připravíme zdarma po krátkém hovoru – a vždy s jasným rozpisem, co v ceně je a co ne.',
        'Neprodáváme balíčky, které nutí platit za funkce, které nepotřebujete. Cenu tvorby webových stránek skládáme podle skutečného rozsahu projektu.'],
    card_h3='V ceně je vždy',
    card=['Návrh struktury a designu', 'Web pro mobil, tablet i počítač', 'Kontaktní formulář a mapa', 'Základní SEO nastavení',
          'Napojení na Google Analytics', 'Cookies lišta a GDPR', 'Zaškolení do administrace', 'Nabídka a konzultace zdarma'],
    grid_head=('Co ovlivňuje cenu', 'Kolik stojí web: 8 faktorů, které rozhodují', 'Dva weby se stejným počtem stránek mohou stát velmi rozdílně. Tady je proč.'),
    grid=[('Počet stránek', 'Jednostránkový web je levnější než web s desítkami podstránek služeb a referencí.'),
          ('Texty', 'Dodáte texty sami, nebo je máme napsat? Kvalitní obsah je práce, ale vyplatí se i pro SEO.'),
          ('Fotky a grafika', 'Vlastní fotky, fotobanka, nebo focení na místě? Logo a vizuální styl jsou samostatná položka.'),
          ('Funkce', 'Rezervace, kalkulačky, filtry, napojení na externí systémy – každá funkce přidá práci.'),
          ('Jazykové verze', 'Němčina nebo polština pro turisty znamená další texty i technické nastavení.'),
          ('E-shop', 'Produkty, platby, doprava a obchodní podmínky – e-shop je samostatná kategorie projektu.'),
          ('Design na míru', 'Úprava osvědčeného rozložení je levnější než úplně originální grafika.'),
          ('Správa po spuštění', 'Aktualizace, zálohy a úpravy můžete řešit sami, nebo je předat nám.')],
    deep_h2='Kolik stojí provoz webu a jde to levně?',
    deep='<p>K ceně tvorby připočítejte provoz. Doména .cz stojí řádově stovky korun ročně, běžný hosting pro WordPress stovky až nižší tisíce korun ročně. Pokud chcete, aby se o aktualizace a zálohy staral někdo jiný, přidejte <a href="/sprava-webu/">správu webu</a>.</p>'
         '<h3>Tvorba webových stránek levně – kde ušetřit</h3><p>Ušetřit se dá rozumně: připravte si podklady, dodejte vlastní fotky, začněte s menším rozsahem a web rozšiřujte postupně. Neušetříte ale na obsahu a struktuře – web bez promyšlených textů nepřivede zákazníky, ať stál kolik chtěl.</p>'
         '<h3>Proč nevolit nejlevnější nabídku</h3><p>Velmi levný web často znamená šablonu bez SEO, bez možnosti úprav, nebo web, ke kterému nemáte přístup. Při porovnání nabídek se ptejte, kdo bude web vlastnit, jak se upravuje a co se stane po spuštění.</p>'
         '<h3>Kolik stojí web, který vydělává?</h3><p>Lepší otázka než „kolik stojí web“ je, kolik vám web přinese. Pokud díky němu získáte pár zakázek ročně navíc, vrátí se investice rychle. Proto navrhujeme každý web s jasnou cestou k poptávce.</p>',
    faq=[('Kolik stojí jednoduchý web?', 'Jednoduchý prezentační web u nás začíná na 9 900 Kč. Přesnou cenu dostanete v nezávazné nabídce.'),
         ('Kolik stojí web s e-shopem?', 'E-shop naceňujeme individuálně podle počtu produktů, plateb, dopravy a napojení. Více na stránce <a href="/tvorba-eshopu/">tvorba e-shopu</a>.'),
         ('Platí se celá částka předem?', 'Ne. Obvykle se platí záloha při zahájení a zbytek po spuštění webu. Podmínky dostanete v nabídce.'),
         ('Kolik stojí úpravy po spuštění?', 'Drobné úpravy zvládnete sami v administraci. Větší změny naceníme předem, případně je zahrneme do správy webu.'),
         ('Kolik stojí web pro živnostníka?', 'Pro většinu živnostníků stačí menší web do deseti stránek, který se vejde do nižších cenových hladin. Rozpočet probereme hned na začátku.')],
),
dict(
    slug='tvorba-webu-wordpress', nav='Tvorba webu WordPress',
    h1='Tvorba webu WordPress', kw='tvorba webu wordpress',
    extra='wordpress tvorba webu,tvorba webových stránek wordpress,tvorba webových stránek s administrací,tvorba webu wordpress cena',
    title='Tvorba webu WordPress: web s administrací | wwwwww.cz',
    desc='Tvorba webu WordPress s Elementorem: web s jednoduchou administrací, který si upravíte sami. Návrh, SEO, zaškolení i správa. Weby od 9 900 Kč.',
    eyebrow='WordPress + Elementor',
    lead='Tvorba webu WordPress s administrací, kterou zvládne každý. Texty, fotky, ceník i nové stránky si upravíte sami – bez programátora a bez čekání.',
    intro_h2='Proč stavíme na WordPressu',
    intro=[
        'WordPress pohání velkou část webů na světě. Je ověřený, má obrovskou komunitu a je pro něj snadné najít pomoc. Pro vás to znamená jistotu, že web nezůstane závislý na jednom dodavateli.',
        'Tvorba webu WordPress u nás jde ruku v ruce s Elementorem – vizuálním editorem, ve kterém upravujete stránky tak, jak je vidí návštěvník. Žádný kód, žádné složité formuláře.',
        'Tvorba webových stránek s administrací ale není jen o systému. Rozhoduje, jak web nastavíme: přehledné bloky, jasné styly a minimum zbytečných pluginů, aby se web snadno udržoval.'],
    card_h3='Co umí váš WordPress web',
    card=['Vizuální úpravy v Elementoru', 'Nové stránky a články bez kódu', 'Formuláře s odesíláním na e-mail', 'SEO plugin Rank Math',
          'Napojení na Google Site Kit', 'Cookies lištu a souhlas GDPR', 'Rozšíření o e-shop WooCommerce', 'Zálohy a aktualizace'],
    grid_head=('Výhody', 'Tvorba webu WordPress: 8 výhod pro vaši firmu', 'Proč je WordPress pro většinu menších firem a živnostníků nejrozumnější volba.'),
    grid=[('Snadná administrace', 'Text nebo fotku změníte za pár minut, bez programátora.'),
          ('Vlastnictví webu', 'Web i data jsou vaše. Můžete ho kdykoli přesunout k jinému hostingu.'),
          ('SEO nástroje', 'Titulky, popisky, sitemapy i strukturovaná data řešíte přímo v administraci.'),
          ('Rozšiřitelnost', 'Rezervace, jazyky, e-shop nebo blog přidáte i později.'),
          ('Komunita', 'Ke WordPressu najdete návody, pluginy i odborníky v celé ČR.'),
          ('Elementor', 'Vizuální editor, ve kterém upravujete stránku přímo tak, jak vypadá.'),
          ('Rozumná cena', 'Díky ověřenému základu platíte za design a obsah, ne za vývoj systému.'),
          ('Bezpečnost', 'Pravidelné aktualizace a zálohy drží web v dobré kondici.')],
    deep_h2='Kdy WordPress a kdy něco jiného',
    deep='<p>Pro prezentační weby, weby služeb, ubytování, obce i menší e-shopy je WordPress výborná volba. U projektů s velmi specifickou logikou, napojením na interní systémy nebo náročnými požadavky na míru sáhneme po October CMS.</p>'
         '<h3>Kolik stojí tvorba webu WordPress</h3><p>Tvorba webu WordPress začíná na 9 900 Kč. Cena roste s počtem stránek, funkcí a jazyků. Podrobný rozpis najdete na stránce <a href="/kolik-stoji-web/">Kolik stojí web</a>.</p>'
         '<h3>Máte starý WordPress web?</h3><p>Pokud máte starší WordPress, který se špatně upravuje nebo vypadá zastarale, nemusíte začínat od nuly. Často stačí <a href="/redesign-webu/">redesign webu</a> s převodem obsahu.</p>'
         '<h3>Zaškolení v ceně</h3><p>Po spuštění vám ukážeme, jak web upravovat. Dostanete i krátký návod, ke kterému se můžete kdykoli vrátit.</p>',
    faq=[('Je WordPress zdarma?', 'Samotný WordPress je open-source a zdarma. Platíte za doménu, hosting, případné prémiové pluginy a hlavně za návrh a realizaci webu.'),
         ('Zvládnu úpravy webu sám?', 'Ano. Díky Elementoru změníte texty, fotky i celé sekce sami. Zaškolení je součástí předání webu.'),
         ('Je WordPress bezpečný?', 'Při pravidelných aktualizacích, zálohách a rozumném výběru pluginů ano. O údržbu se můžeme postarat v rámci správy webu.'),
         ('Můžete převzít můj stávající WordPress?', 'Ano. Projdeme ho, navrhneme úpravy a případně se postaráme o jeho další správu.'),
         ('Dá se na WordPressu postavit e-shop?', 'Ano, pomocí WooCommerce. Pro menší a střední e-shopy je to osvědčené řešení.')],
),
dict(
    slug='tvorba-webu-na-miru', nav='Tvorba webu na míru',
    h1='Tvorba webu na míru', kw='tvorba webu na míru',
    extra='tvorba webových stránek na míru,tvorba webu na zakázku,tvorba webových stránek na zakázku',
    title='Tvorba webu na míru: 8 kroků k webu, který prodává',
    desc='Tvorba webu na míru i na zakázku: struktura, texty a design přizpůsobené vašemu oboru a zákazníkům. Osobní přístup, SEO a weby od 9 900 Kč.',
    eyebrow='Web na zakázku',
    lead='Tvorba webu na míru pro firmy, které nechtějí vypadat jako všichni ostatní. Struktura, texty i design přizpůsobené vašemu oboru, zákazníkům a cílům.',
    intro_h2='Co znamená web na míru',
    intro=[
        'Web na míru není jen originální grafika. Je to web, jehož struktura odpovídá tomu, jak se vaši zákazníci rozhodují, a jehož texty mluví jejich jazykem.',
        'Tvorba webu na míru proto začíná analýzou: kdo jsou vaši zákazníci, co hledají na Googlu, co nabízí konkurence a čím se odlišujete. Na tom stavíme strukturu, obsah i design.',
        'Tvorba webových stránek na zakázku zároveň neznamená, že musíte platit za vývoj od nuly. Kombinujeme osvědčené technologie s designem a obsahem šitým přesně pro vás.'],
    card_h3='Na míru připravíme',
    card=['Strukturu podle vašich zákazníků', 'Texty v jazyce vašeho oboru', 'Design ve stylu vaší značky', 'Funkce, které opravdu použijete',
          'SEO podle toho, co lidé hledají', 'Napojení na vaše nástroje', 'Administraci pro váš tým', 'Plán dalšího rozvoje'],
    grid_head=('Postup', 'Tvorba webu na míru v 8 krocích', 'Od analýzy po spuštění – každý krok přizpůsobený vašemu projektu.'),
    grid=[('Analýza', 'Zákazníci, konkurence, klíčová slova a cíle webu.'),
          ('Struktura', 'Mapa stránek a cesta návštěvníka k poptávce.'),
          ('Obsah', 'Texty, které vysvětlí, prodávají a fungují ve vyhledávačích.'),
          ('Wireframe', 'Rozložení klíčových stránek ještě před grafikou.'),
          ('Design', 'Grafický návrh na míru vaší značce a oboru.'),
          ('Vývoj', 'WordPress s Elementorem, nebo October CMS pro specifické projekty.'),
          ('Testování', 'Kontrola na mobilech, formulářů, měření i SEO.'),
          ('Spuštění a rozvoj', 'Spuštění, vyhodnocení a další vylepšování podle dat.')],
    deep_h2='Web na míru, nebo šablona?',
    deep='<p>Šablona může stačit, pokud potřebujete rychle jednoduchou vizitku. Jakmile ale chcete, aby web přiváděl poptávky, odlišil vás od konkurence a dobře se umisťoval ve vyhledávání, vyplatí se tvorba webu na míru.</p>'
         '<h3>Tvorba webových stránek na zakázku pro konkrétní obor</h3><p>Kadeřnictví potřebuje online rezervace, penzion fotky a dostupnost, stavební firma reference a poptávkový formulář. Pro více než 70 oborů jsme sepsali, co by měl web mít – najdete je v přehledu <a href="/weby-pro-obory/">weby pro obory</a>.</p>'
         '<h3>Kolik stojí web na míru</h3><p>Cena závisí na rozsahu, funkcích a podílu práce na obsahu. Weby začínají na 9 900 Kč, projekt na míru vždy naceníme individuálně. Více na stránce <a href="/kolik-stoji-web/">Kolik stojí web</a>.</p>'
         '<h3>Osobní přístup</h3><p>Po celou dobu máte jednoho člověka, se kterým vše řešíte. Žádné předávání mezi odděleními a žádné nejasnosti.</p>',
    faq=[('Jaký je rozdíl mezi webem na míru a šablonou?', 'Web na míru má strukturu, texty i design přizpůsobené vašemu podnikání. Šablona je univerzální a často vypadá podobně jako weby konkurence.'),
         ('Jak dlouho trvá tvorba webu na míru?', 'Podle rozsahu obvykle 3–8 týdnů. Harmonogram dostanete v nabídce.'),
         ('Budu si moci web na míru upravovat sám?', 'Ano. I web na míru stavíme tak, abyste texty, fotky a stránky upravovali sami.'),
         ('Děláte i weby na zakázku pro větší firmy?', 'Ano. Pro rozsáhlejší projekty spolupracujeme s týmem agentury Yesmark – od brandingu po kampaně.'),
         ('Co když nevím přesně, co chci?', 'To je v pořádku. Právě proto začínáme analýzou a konzultací, kde společně ujasníme cíle.')],
),
dict(
    slug='tvorba-eshopu', nav='Tvorba e-shopu',
    h1='Tvorba e-shopu', kw='tvorba e-shopu',
    extra='tvorba eshopu,tvorba e-shopu na míru,e-shop na míru',
    title='Tvorba e-shopu: 8 věcí, na kterých záleží | wwwwww.cz',
    desc='Tvorba e-shopu na míru na WooCommerce nebo PrestaShopu. Přehledný obchod, platby, doprava, SEO i zaškolení. Nabídku připravíme zdarma.',
    eyebrow='E-shopy',
    lead='Tvorba e-shopu, ve kterém se zákazníci snadno vyznají a nakoupí. Přehledné kategorie, jednoduchý košík, platby a doprava – a administrace, kterou zvládnete sami.',
    intro_h2='E-shop, který prodává, ne jen vystavuje',
    intro=[
        'Úspěšný e-shop nestojí na množství funkcí, ale na tom, jak snadno zákazník najde produkt, pochopí jeho výhody a dokončí objednávku. Tvorba e-shopu u nás proto začíná u nákupní cesty zákazníka.',
        'E-shopy stavíme na WooCommerce (WordPress) nebo PrestaShopu – podle počtu produktů, požadavků na napojení a toho, jak chcete obchod spravovat.',
        'Tvorba e-shopu na míru zahrnuje i obchodní podmínky, GDPR, napojení plateb a dopravců a základní SEO kategorií a produktů.'],
    card_h3='Součástí e-shopu',
    card=['Katalog produktů a kategorií', 'Košík a objednávka na pár kliků', 'Platební brána a převod', 'Napojení na dopravce',
          'Obchodní podmínky a GDPR', 'SEO kategorií a produktů', 'Měření prodejů v Analytics', 'Zaškolení do administrace'],
    grid_head=('Checklist', 'Tvorba e-shopu: 8 věcí, na kterých záleží', 'Na těchto bodech se rozhoduje, jestli zákazník nakoupí, nebo odejde ke konkurenci.'),
    grid=[('Jasná navigace', 'Kategorie a filtry, ve kterých se zákazník vyzná bez přemýšlení.'),
          ('Kvalitní produktové stránky', 'Fotky, popis, parametry a dostupnost na jednom místě.'),
          ('Důvěra', 'Kontakty, recenze, obchodní podmínky a jasné informace o vrácení.'),
          ('Jednoduchá objednávka', 'Co nejméně kroků a polí, nákup i bez registrace.'),
          ('Platby a doprava', 'Oblíbené platební metody a výdejní místa.'),
          ('Mobil', 'Většina zákazníků nakupuje z telefonu – e-shop musí fungovat na mobilu.'),
          ('SEO', 'Unikátní texty kategorií a produktů, které Google dokáže najít.'),
          ('Měření', 'Víte, odkud zákazníci přicházejí a co nakupují.')],
    deep_h2='WooCommerce, nebo PrestaShop?',
    deep='<p>WooCommerce je ideální pro menší a střední e-shopy, které chtějí spojit obchod s obsahovým webem a jednoduchou administrací. PrestaShop se hodí pro obchody s větším katalogem a specifickými požadavky.</p>'
         '<h3>Kolik stojí tvorba e-shopu</h3><p>Cenu ovlivňuje počet produktů, import dat, platby, doprava a napojení na účetnictví nebo sklad. Tvorbu e-shopu naceňujeme individuálně a nabídku připravíme zdarma.</p>'
         '<h3>Máte už prezentační web?</h3><p>Pokud máte web na WordPressu, můžeme e-shop přidat přímo do něj. Pokud je web zastaralý, zvažte <a href="/redesign-webu/">redesign webu</a> spolu se spuštěním obchodu.</p>'
         '<h3>Propagace po spuštění</h3><p>E-shop potřebuje návštěvnost. S agenturou Yesmark navážeme PPC kampaněmi, sociálními sítěmi a <a href="/seo-optimalizace-webu/">SEO optimalizací</a>.</p>',
    faq=[('Jak dlouho trvá tvorba e-shopu?', 'Menší e-shop bývá hotový za 4–8 týdnů. Záleží hlavně na počtu produktů a napojení.'),
         ('Pomůžete s importem produktů?', 'Ano. Produkty můžeme naimportovat z tabulky nebo z XML feedu dodavatele.'),
         ('Napojíte e-shop na účetnictví?', 'Napojení na běžné fakturační a účetní systémy je možné. Konkrétní řešení probereme v nabídce.'),
         ('Budu si produkty přidávat sám?', 'Ano. Přidávání produktů, úprava cen a vyřizování objednávek zvládnete v administraci.'),
         ('Řešíte i obchodní podmínky?', 'Pomůžeme s jejich strukturou a umístěním na webu. Právní text doporučujeme nechat zkontrolovat odborníkem.')],
),
dict(
    slug='redesign-webu', nav='Redesign webu',
    h1='Redesign webu', kw='redesign webu',
    extra='předělání webu,nový web místo starého,modernizace webu',
    title='Redesign webu: 8 signálů, že je čas | wwwwww.cz',
    desc='Redesign webu, který nic nepřináší: nový design, obsah a struktura zaměřená na poptávky. Zachováme pozice ve vyhledávání. Nabídka zdarma.',
    eyebrow='Nový web místo starého',
    lead='Redesign webu pro firmy, které mají web, ale ten jim nic nepřináší. Převlékneme ho do moderního kabátu, přepíšeme obsah a postavíme znovu – tentokrát na poptávky.',
    intro_h2='Kdy dává redesign webu smysl',
    intro=[
        'Web zastarává rychleji, než si myslíte. Co před pár lety vypadalo moderně, dnes působí neprofesionálně a na mobilu se špatně ovládá. Zákazník si pak udělá názor na celou firmu.',
        'Redesign webu ale není jen nová grafika. Projdeme, co na současném webu funguje, co ne, a odkud přicházejí návštěvníci. Na tom postavíme novou strukturu, obsah i design.',
        'Důležité je zachovat to, co už máte: pozice ve vyhledávání, odkazy a obsah, který funguje. Proto při redesignu řešíme i přesměrování starých adres.'],
    card_h3='Při redesignu řešíme',
    card=['Audit současného webu', 'Novou strukturu a texty', 'Moderní design pro mobil', 'Převod obsahu a fotek',
          'Přesměrování starých adres', 'Zachování SEO pozic', 'Snadnou administraci', 'Měření výsledků'],
    grid_head=('Signály', 'Redesign webu: 8 signálů, že je čas', 'Pokud poznáváte svůj web ve více bodech, vyplatí se o redesignu přemýšlet.'),
    grid=[('Nevypadá dobře na mobilu', 'Text je malý, tlačítka těžko trefitelná, menu nefunguje.'),
          ('Nepřichází poptávky', 'Návštěvníci odcházejí, aniž by zavolali nebo napsali.'),
          ('Neodpovídá firmě', 'Služby, ceny nebo fotky už neodpovídají realitě.'),
          ('Nejde upravovat', 'Každá změna znamená volat programátora.'),
          ('Nenajde vás Google', 'Na důležité fráze se web neukazuje.'),
          ('Zastaralý vzhled', 'Web působí jako z jiné doby a podkopává důvěru.'),
          ('Chybí GDPR a cookies', 'Starý web nesplňuje dnešní požadavky na souhlas s cookies.'),
          ('Chcete víc', 'Rezervace, jazyky nebo e-shop, které starý web neumí.')],
    deep_h2='Jak probíhá redesign webu',
    deep='<p>Začínáme auditem: projdeme obsah, strukturu, návštěvnost a to, na co se web ve vyhledávání ukazuje. Poté navrhneme novou strukturu, připravíme texty a design. Nový web spustíme tak, aby staré adresy vedly na nové stránky.</p>'
         '<h3>Redesign webu bez ztráty pozic</h3><p>Největší riziko redesignu je ztráta návštěvnosti z Googlu. Proto mapujeme staré adresy, nastavujeme přesměrování a po spuštění kontrolujeme Search Console.</p>'
         '<h3>Redesign, nebo úplně nový web?</h3><p>Pokud je současný web na WordPressu a obsah je v pořádku, často stačí nový design a úprava struktury. Pokud ne, postavíme <a href="/tvorba-webu-na-miru/">nový web na míru</a> a obsah převedeme.</p>'
         '<h3>Kolik stojí redesign webu</h3><p>Cena závisí na rozsahu webu a množství obsahu k převodu. Orientační přehled najdete na stránce <a href="/kolik-stoji-web/">Kolik stojí web</a>, přesnou nabídku připravíme zdarma.</p>',
    faq=[('Přijdu redesignem o pozice v Googlu?', 'Při správném postupu ne. Hlídáme přesměrování starých adres, zachování obsahu i technické SEO.'),
         ('Můžete převzít obsah ze starého webu?', 'Ano. Obsah převedeme a zároveň ho upravíme, aby lépe prodával.'),
         ('Jak dlouho trvá redesign webu?', 'Obvykle 3–6 týdnů podle rozsahu a množství obsahu.'),
         ('Zůstane mi doména a e-maily?', 'Ano. Doménu i e-maily zachováme, měníme jen samotný web.'),
         ('Musí být starý web na WordPressu?', 'Nemusí. Redesign uděláme pro web na jakémkoli systému – obsah převedeme do nového řešení.')],
),
dict(
    slug='sprava-webu', nav='Správa webu',
    h1='Správa webu', kw='správa webu',
    extra='správa webových stránek,údržba webu,správa wordpress webu',
    title='Správa webu: 8 věcí, o které se postaráme | wwwwww.cz',
    desc='Správa webu a údržba WordPressu: aktualizace, zálohy, zabezpečení, úpravy obsahu i propagace. Vy podnikáte, o web se postaráme my.',
    eyebrow='Údržba a péče',
    lead='Správa webu pro firmy, které chtějí mít web v pořádku, ale nechtějí se o něj starat. Aktualizace, zálohy, zabezpečení i úpravy obsahu – vše na jednom místě.',
    intro_h2='Web potřebuje péči i po spuštění',
    intro=[
        'Web není hotový dnem spuštění. Systém a pluginy potřebují aktualizace, obsah zastarává a konkurence nespí. Bez pravidelné péče se z dobrého webu postupně stává problém.',
        'Správa webu u nás znamená, že máte jednoho člověka, kterému napíšete, když potřebujete cokoli změnit. Úpravy, nové stránky, akce nebo změny ceníku – vyřešíme za vás.',
        'Spravujeme weby, které jsme postavili, i weby od jiných dodavatelů. Na začátku web projdeme a navrhneme, co je potřeba opravit.'],
    card_h3='Správa webu zahrnuje',
    card=['Aktualizace WordPressu a pluginů', 'Pravidelné zálohy', 'Kontrola zabezpečení', 'Úpravy textů a fotek',
          'Nové stránky a sekce', 'Kontrolu formulářů', 'Dohled nad Search Console', 'Konzultace k rozvoji webu'],
    grid_head=('Co hlídáme', 'Správa webu: 8 věcí, o které se postaráme', 'Pravidelná péče, díky které web funguje a nepřestane přivádět zákazníky.'),
    grid=[('Aktualizace', 'WordPress, šablona i pluginy vždy v aktuální verzi.'),
          ('Zálohy', 'Pravidelné zálohy pro případ, že se něco pokazí.'),
          ('Zabezpečení', 'Kontrola přístupů, hesel a podezřelé aktivity.'),
          ('Obsah', 'Úpravy textů, ceníků, fotek a akcí podle vašich požadavků.'),
          ('Formuláře', 'Ověřujeme, že poptávky z webu skutečně dorazí.'),
          ('SEO', 'Sledujeme Search Console a opravujeme chyby indexace.'),
          ('Cookies a GDPR', 'Lišta a dokumenty v souladu s aktuálními pravidly.'),
          ('Rozvoj', 'Návrhy na vylepšení podle návštěvnosti a poptávek.')],
    deep_h2='Proč nesvěřit správu webu náhodě',
    deep='<p>Neaktualizovaný WordPress je častým cílem útoků. Nefunkční formulář znamená ztracené poptávky, o kterých nevíte. A zastaralý obsah odrazuje zákazníky. Pravidelná správa webu těmto problémům předchází.</p>'
         '<h3>Propagace a kampaně</h3><p>Se správou webu umíme navázat i propagací: PPC kampaně, sociální sítě a <a href="/seo-optimalizace-webu/">SEO optimalizace</a> zajišťuje tým agentury Yesmark.</p>'
         '<h3>Převezmeme i cizí web</h3><p>Máte web od jiného dodavatele, který už nereaguje? Web projdeme, zazálohujeme a převezmeme. Pokud je zastaralý, navrhneme <a href="/redesign-webu/">redesign webu</a>.</p>'
         '<h3>Kolik stojí správa webu</h3><p>Cena správy webu závisí na velikosti webu a rozsahu úprav. Nabízíme pravidelnou měsíční správu i jednorázové zásahy podle potřeby.</p>',
    faq=[('Spravujete i weby, které jste nedělali?', 'Ano. Na začátku web projdeme, zazálohujeme a navrhneme, co je potřeba opravit.'),
         ('Jak rychle reagujete na úpravy?', 'Běžné úpravy obvykle během několika pracovních dní. Termín vždy domluvíme předem.'),
         ('Co když se web rozbije?', 'Díky pravidelným zálohám web obnovíme a zjistíme příčinu problému.'),
         ('Mohu si některé úpravy dělat sám?', 'Samozřejmě. Správa webu nevylučuje, abyste si drobné změny dělali sami v administraci.'),
         ('Řešíte i hosting a doménu?', 'Ano. Pomůžeme s prodloužením domény, hostingem i nastavením e-mailů.')],
),
dict(
    slug='seo-optimalizace-webu', nav='SEO optimalizace webu',
    h1='SEO optimalizace webu', kw='seo optimalizace webu',
    extra='tvorba webových stránek seo,seo optimalizace,lokální seo',
    title='SEO optimalizace webu: 8 kroků, jak vás najde Google',
    desc='SEO optimalizace webu pro firmy a živnostníky: struktura, obsah, technické SEO, lokální SEO a Google Firemní profil. Aby vás zákazníci našli.',
    eyebrow='SEO',
    lead='SEO optimalizace webu, aby vás zákazníci našli dřív než konkurenci. Struktura, obsah, technické SEO i Google Firemní profil – srozumitelně a bez zbytečných slibů.',
    intro_h2='SEO začíná už při tvorbě webu',
    intro=[
        'Nejlevnější SEO je to, které se udělá hned při tvorbě webu. Promyšlená struktura, správné nadpisy, popisky a interní odkazy dají webu dobrý základ, na kterém se dá stavět.',
        'Proto u nás tvorba webových stránek a SEO jdou ruku v ruce. Každý web, který postavíme, má základní SEO optimalizaci v ceně. Pro větší ambice nabízíme navazující optimalizaci a obsah.',
        'SEO optimalizace webu ale není kouzlo. Výsledky přicházejí postupně, v řádu týdnů až měsíců. Slibujeme poctivou práci, ne první místo na Googlu za týden.'],
    card_h3='Co optimalizujeme',
    card=['Strukturu webu a interní odkazy', 'Titulky a meta popisky', 'Nadpisy a obsah stránek', 'Alt texty obrázků',
          'Sitemapu a indexaci', 'Strukturovaná data', 'Google Firemní profil', 'Měření v Search Console'],
    grid_head=('Postup', 'SEO optimalizace webu v 8 krocích', 'Jak postupujeme, aby váš web získal návštěvnost z vyhledávání.'),
    grid=[('Analýza klíčových slov', 'Zjistíme, co vaši zákazníci skutečně hledají.'),
          ('Audit webu', 'Najdeme technické chyby, duplicity a slabá místa.'),
          ('Struktura', 'Každé důležité téma dostane vlastní stránku.'),
          ('Obsah', 'Texty, které odpovídají na otázky zákazníků.'),
          ('On-page SEO', 'Titulky, popisky, nadpisy, alt texty a interní odkazy.'),
          ('Lokální SEO', 'Google Firemní profil, recenze a lokální stránky.'),
          ('Indexace', 'Sitemapa, Search Console a kontrola chyb.'),
          ('Vyhodnocení', 'Sledujeme pozice a návštěvnost a obsah dále ladíme.')],
    deep_h2='Lokální SEO pro firmy z regionu',
    deep='<p>Pokud obsluhujete zákazníky v konkrétním městě, je lokální SEO nejrychlejší cesta k výsledkům. Optimalizujeme Google Firemní profil, vytváříme stránky pro jednotlivá města a pomáháme se sbíráním recenzí.</p>'
         '<h3>Tvorba webových stránek se SEO od začátku</h3><p>U nových webů je SEO optimalizace webu součástí tvorby. U stávajících webů začínáme auditem a navrhneme, co upravit. Někdy stačí doplnit obsah, jindy se vyplatí <a href="/redesign-webu/">redesign webu</a>.</p>'
         '<h3>Obsah, který přivádí zákazníky</h3><p>Pro desítky oborů jsme sepsali, co by měl web obsahovat – podívejte se do přehledu <a href="/weby-pro-obory/">weby pro obory</a>. Stejný přístup použijeme i pro váš web.</p>'
         '<h3>SEO, PPC a sociální sítě</h3><p>SEO je dlouhodobá investice. Pokud potřebujete výsledky hned, doplníme ho PPC kampaněmi s týmem agentury Yesmark.</p>',
    faq=[('Za jak dlouho uvidím výsledky SEO?', 'První změny obvykle během několika týdnů, výraznější výsledky v řádu měsíců. Záleží na konkurenci v oboru.'),
         ('Zaručíte první místo na Googlu?', 'Ne. První místo nikdo poctivě zaručit nemůže. Garantujeme kvalitní práci a průběžné vyhodnocení.'),
         ('Je SEO součástí tvorby webu?', 'Ano. Každý nový web má základní SEO optimalizaci v ceně.'),
         ('Co je Google Firemní profil?', 'Bezplatný profil firmy na Mapách a ve vyhledávání Google. Pro lokální firmy je zásadní.'),
         ('Děláte SEO i pro weby od jiných dodavatelů?', 'Ano. Začneme auditem a navrhneme konkrétní kroky.')],
),
dict(
    slug='firemni-web', nav='Firemní web',
    h1='Firemní web', kw='firemní web',
    extra='firemní webové stránky,web pro firmu,tvorba firemního webu',
    title='Firemní web: 8 věcí, které musí mít | wwwwww.cz',
    desc='Firemní web, který buduje důvěru a přivádí poptávky. Co by měl obsahovat, jak má vypadat a kolik stojí. Tvorba firemních webů od 9 900 Kč.',
    eyebrow='Web pro firmu',
    lead='Firemní web je často první, co o vás zákazník uvidí. Ukážeme, co by měl obsahovat, aby budoval důvěru, vysvětlil vaše služby a přivedl poptávky.',
    intro_h2='K čemu je firemní web',
    intro=[
        'Zákazník, který o vás slyšel od známého nebo vás našel na mapách, si skoro vždy otevře web. Během pár vteřin se rozhodne, jestli působíte důvěryhodně a jestli děláte to, co hledá.',
        'Dobrý firemní web proto jasně řekne, co děláte, pro koho a proč právě vy. Ukáže reference, ceny nebo alespoň orientační rozsah a nabídne jednoduchý způsob, jak vás kontaktovat.',
        'Firemní web zároveň slouží jako podklad pro další marketing: Google Firemní profil, sociální sítě, PPC kampaně i tištěné materiály odkazují právě na něj.'],
    card_h3='Firemní web by měl mít',
    card=['Jasné sdělení na první obrazovce', 'Přehled služeb nebo produktů', 'Reference a ukázky práce', 'Informace o firmě a týmu',
          'Kontakty a mapu', 'Poptávkový formulář', 'Web pro mobil', 'Základní SEO'],
    grid_head=('Checklist', 'Firemní web: 8 věcí, které musí mít', 'Osm bodů, podle kterých poznáte, jestli váš web pracuje pro firmu.'),
    grid=[('Jasné sdělení', 'Na první pohled je jasné, co děláte a pro koho.'),
          ('Služby', 'Každá důležitá služba má vlastní stránku.'),
          ('Reference', 'Ukázky práce, loga klientů nebo hodnocení.'),
          ('Důvěra', 'Skuteční lidé, fotky týmu, certifikáty a roky na trhu.'),
          ('Kontakt', 'Telefon, e-mail a formulář vždy po ruce.'),
          ('Mobil', 'Pohodlné ovládání na telefonu.'),
          ('SEO', 'Struktura a texty, díky kterým vás najde Google.'),
          ('Měření', 'Víte, kolik poptávek web přinesl.')],
    deep_h2='Jak postavit firemní web, který funguje',
    deep='<p>Firemní web stavíme podle toho, jak se vaši zákazníci rozhodují. Výrobní firma potřebuje ukázat technologie a kapacity, služba reference a rychlý kontakt, ubytování fotky a rezervace. Inspiraci pro desítky oborů najdete v přehledu <a href="/weby-pro-obory/">weby pro obory</a>.</p>'
         '<h3>Firemní web, nebo e-shop?</h3><p>Pokud prodáváte produkty online, zvažte <a href="/tvorba-eshopu/">tvorbu e-shopu</a>. Pokud nabízíte služby nebo zakázkovou výrobu, firemní web s poptávkovým formulářem je obvykle lepší volba.</p>'
         '<h3>Kolik stojí firemní web</h3><p>Firemní web u nás začíná na 9 900 Kč. Cena závisí na počtu stránek, funkcích a podílu práce na textech. Více na stránce <a href="/kolik-stoji-web/">Kolik stojí web</a>.</p>'
         '<h3>Jednotná značka</h3><p>S agenturou Yesmark navážeme logem, vizuálním stylem, tiskovinami i reklamními předměty, aby firma působila jednotně online i offline.</p>',
    faq=[('Kolik stránek by měl mít firemní web?', 'Většině firem stačí 5–15 stránek: úvod, služby, reference, o firmě a kontakt. Každá klíčová služba si zaslouží vlastní stránku.'),
         ('Co když nemáme texty?', 'Pomůžeme s nimi. Stačí nám informace o firmě a službách, texty připravíme a doladíme s vámi.'),
         ('Potřebujeme profesionální fotky?', 'Vlastní fotky působí výrazně důvěryhodněji než fotobanka. Pokud je nemáte, doporučíme fotografa.'),
         ('Můžeme mít web ve více jazycích?', 'Ano. Jazykové verze přidáme hned, nebo později.'),
         ('Jak dlouho trvá vytvoření firemního webu?', 'Obvykle 2–6 týdnů podle rozsahu a podkladů.')],
),
]
